Repository wp-graphql/wp-graphql, pull requests merged in 2019-12, with the labels that each got.

#1051 #1050 - Add display name to the User Role type and update description of the "name" field
  src/Data/DataSource.php
  src/Model/UserRole.php
  src/Type/Object/UserRole.php
  tests/wpunit/UserRoleConnectionQueriesTest.php
Labels: Enhancement

#1055 Release/v0.4.3
  access-functions.php
  src/Data/DataSource.php
  src/Model/UserRole.php
  src/Registry/TypeRegistry.php
  src/Router.php
  src/Type/Object/UserRole.php
  tests/wpunit/TypesTest.php
  tests/wpunit/UserRoleConnectionQueriesTest.php
  wp-graphql.php
Labels: Release

#1056 Release/v0.5.0
  docs/gatsby-config.js
  docs/source/extending/types.mdx
  docs/src/gatsby-theme-apollo-docs/components/page-layout.js
  src/Connection/PostObjects.php
  src/Connection/Revisions.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/UserLoader.php
  src/Model/Post.php
  src/Registry/TypeRegistry.php
  src/Type/Object/PostObject.php
  src/Type/Union/ContentRevisionUnion.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/RevisionTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1060 #944 - Query Multiple Post Types in PostObjectConnectionResolver
  src/Data/Connection/PostObjectConnectionResolver.php
  vendor/composer/autoload_framework_classmap.php
Labels: Enhancement

#1069 #964 - grapqhl() function breaks when used in page templates
  src/Request.php
Labels: Bug

#1073 #1071 - User Pagination not working in docs
  docs/package.json
  docs/src/components/GraphiQL/index.js
  docs/yarn.lock
Labels: Documentation

#1074 #1063 - Z-Index issue for GraphiQL in Docs
  docs/src/components/GraphiQL/style.css
Labels: Bug, Documentation

#1076 Release/v0.5.1
  docs/package.json
  docs/src/components/GraphiQL/index.js
  docs/src/components/GraphiQL/style.css
  docs/yarn.lock
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Request.php
  src/Router.php
  src/Type/Object/RootQuery.php
  src/Type/WPUnionType.php
  tests/wpunit/IsGraphqlHttpRequestTest.php
  tests/wpunit/PostObjectQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1084 adds support for post_format as a taxonomy
  tests/wpunit/PostTypeObjectQueriesTest.php
  wp-graphql.php
Labels: Enhancement

#1089 #1088 - Add list_of and non_null methods to TypeRegistry
  src/Registry/TypeRegistry.php
  src/Type/WPObjectType.php
  tests/wpunit/TypesTest.php
Labels: Review Ready

#1099 #1096 - Throw Exception when PHP version is lower than the required PHP version
  docs/source/guides/debugging.mdx
  wp-graphql.php
Labels: Enhancement
