Repository wp-graphql/wp-graphql, pull requests merged in 2019-09, with the labels that each got.

#936 #935 - Check for authentication errors prior to execution.
  src/Request.php
Labels: Enhancement, Security, impact: high

#952 v0.3.6
  README.md
  src/Connection/Users.php
  src/Data/Config.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/UserCursor.php
  src/Request.php
  src/Type/Enum/UsersConnectionOrderbyEnum.php
  src/Type/Input/UsersConnectionOrderbyInput.php
  src/TypeRegistry.php
  tests/wpunit/UserObjectCursorTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_static.php
Labels: Release

#953 v0.3.6
  README.md
  src/Connection/Users.php
  src/Data/Config.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/UserCursor.php
  src/Request.php
  src/Type/Enum/UsersConnectionOrderbyEnum.php
  src/Type/Input/UsersConnectionOrderbyInput.php
  src/TypeRegistry.php
  tests/wpunit/UserObjectCursorTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#959 Feature/#958 add getters to abstract connection resolver
  src/Connection/Users.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/UserCursor.php
  src/Request.php
  src/Type/Enum/UsersConnectionOrderbyEnum.php
  src/Type/Input/UsersConnectionOrderbyInput.php
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_framework_classmap.php
Labels: Enhancement

#950 sourceURL returns file attachment url if file is not an image
  src/Model/Post.php
  src/Type/Object/PostObject.php
  tests/_data/media/test.pdf
  tests/wpunit/MediaItemQueriesTest.php
Labels: Bug, Review Ready, Work In Progress, effort: low, impact: high, status: awaiting author response
