Repository wp-graphql/wp-graphql, pull requests merged in 2019-11, with the labels that each got.

#1018 #992 - follow-up.
  src/Data/Connection/AbstractConnectionResolver.php
Labels: Bug, impact: med

#1015 Update PostObjectCursor.php
  src/Data/Cursor/PostObjectCursor.php
Labels: Bug, Enhancement

#1005 interface field hook implemented
  src/Type/InterfaceType/Node.php
  src/Type/Object/Comment.php
  src/Type/Object/CommentAuthor.php
  src/Type/Object/Menu.php
  src/Type/Object/MenuItem.php
  src/Type/Object/Plugin.php
  src/Type/Object/PostObject.php
  src/Type/Object/PostType.php
  src/Type/Object/Taxonomy.php
  src/Type/Object/TermObject.php
  src/Type/Object/Theme.php
  src/Type/Object/User.php
  src/Type/Object/UserRole.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/MenuItemQueriesTest.php
Labels: Needs Discussion, status: awaiting reviewer response

#1022 Adds more strict check to "is_graphql_request()"
  src/Router.php
Labels: Bug, Enhancement

#1027 Feature/#1024 graphql request condition
  access-functions.php
  src/Data/Config.php
  src/Request.php
  tests/wpunit/DataConfigTest.php
  tests/wpunit/PostObjectCursorTest.php
  tests/wpunit/ThemeConnectionQueriesTest.php
  tests/wpunit/UserObjectCursorTest.php
  wp-graphql.php
Labels: effort: low, impact: med

#1039 Release/v0.4.2
  src/Registry/TypeRegistry.php
  src/Type/WPInputObjectType.php
  src/Type/WPObjectType.php
  tests/wpunit/AccessFunctionsTest.php
  vendor/autoload.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1044 #1043 - Don't call for allowed_types at the init hook
  wp-graphql.php
Labels: Bug, Extensions, effort: low, impact: high
