Repository wp-graphql/wp-graphql, pull requests merged in 2019-01, with the labels that each got.

#637 Feature/#636 pass connection args through context
  src/AppContext.php
  src/TypeRegistry.php
Labels: Architecture, Enhancement

#621 Create a Request class to consolidate WPGraphQL entrypoints.
  access-functions.php
  src/Request.php
  src/Router.php
  src/Server/WPHelper.php
  tests/wpunit/RequestTest.php
  tests/wpunit/WPHelperTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Architecture, Extensions

#662 🐛 FIX: Fixes PHP warnings in the Request class
  src/Request.php
Labels: Bug

#669 👌 IMPROVE: make connection methods public
  src/Connection/Comments.php
  src/Connection/MenuItems.php
  src/Connection/Menus.php
  src/Connection/Plugins.php
  src/Connection/PostObjects.php
  src/Connection/TermObjects.php
  src/Connection/Themes.php
  src/Connection/UserRoles.php
  src/Connection/Users.php
Labels: Enhancement, Work In Progress
