Repository wp-graphql/wp-graphql, pull requests merged in 2019-05, with the labels that each got.

#850 #849 - This ensures that list_of and non_null can be used with each other
  src/TypeRegistry.php
Labels: Bug

#853 #839 - Fix typo with cssClasses
  src/Model/MenuItem.php
  src/TypeRegistry.php
Labels: Bug

#821 Make the post date field to conform to RFC3339
  src/Model/Post.php
  src/Type/Object/EditLock.php
  src/TypeRegistry.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/PostObjectQueriesTest.php
Labels: Bug, Tests

#856 #802 - Throw exception for invalid list_of / non_null Types
  src/TypeRegistry.php
Labels: Enhancement

#857 #260 -
  tests/functional/ApolloPreflightRequestCept.php
Labels: Tests

#858 #796 - Add srcSet field to media items
  src/Model/Post.php
  src/Type/Object/PostObject.php
  tests/wpunit/MediaItemQueriesTest.php
Labels: Enhancement

#867 Release/v0.3.4
  .gitignore
  .travis.yml
  CHANGELOG.md
  Dockerfile.test-base
  README.md
  docker/docker-compose.local-app-xdebug.yml
  docker/docker-compose.local-app.yml
  docker/docker-compose.tests.yml
  list-mysql-containers.sh
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Cursor/PostObjectCursor.php
  src/Model/MenuItem.php
  src/Model/Post.php
  src/Type/Object/EditLock.php
  src/Type/Object/MenuItem.php
  src/Type/Object/PostObject.php
  src/Type/Union/MenuItemObjectUnion.php
  src/TypeRegistry.php
  tests/functional/ApolloPreflightRequestCept.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/PostObjectCursorTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/PostObjectQueriesTest.php
  wp-graphql.php
Labels: Release
