Repository wp-graphql/wp-graphql, pull requests merged in 2020-07, with the labels that each got.

#1355 Release v0.10.1
  docs/source/getting-started/categories-and-tags.mdx
  docs/source/getting-started/comments.mdx
  docs/source/getting-started/custom-fields-and-meta.mdx
  docs/source/getting-started/custom-post-types.mdx
  docs/source/getting-started/custom-taxonomies.mdx
  docs/source/getting-started/interacting-with-wpgraphql.mdx
  docs/source/getting-started/menus.mdx
  docs/source/getting-started/pages.mdx
  docs/source/getting-started/plugins.mdx
  docs/source/getting-started/posts.mdx
  docs/source/getting-started/settings.mdx
  docs/source/getting-started/themes.mdx
  docs/source/getting-started/users.mdx
  docs/source/guides/query-batching.mdx
  docs/source/images/ant-design-checkbox-tree.png
  docs/source/images/ant-design-dropdown-menu.png
  docs/yarn.lock
  src/Registry/TypeRegistry.php
  src/Type/Object/SettingGroup.php
  wp-graphql.php
Labels: Bug, Release

#1366 Bug/#1352 query page with slash doesnt return homepage
  src/Data/DataSource.php
  src/Data/NodeResolver.php
  src/Type/Object/RootQuery.php
  tests/wpunit/NodeByUriTest.php
Labels: Bug, Component: Input, Component: Query, ObjectType: Post, Review Ready, impact: med

#1363 #1219 - Fix circular connections from MenuItems
  src/Connection/MenuItemLinkableConnection.php
  src/Connection/PostObjects.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/Object/MenuItem.php
  src/Type/Object/PostObject.php
  src/Type/Object/TermObject.php
  src/Type/Union/MenuItemObjectUnion.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: Bug, Component: Connections, Component: Interfaces, Component: Query, ObjectType: Menu, Review Ready, effort: low, impact: med

#1370 Add field isPostsPage to check if page is the main posts archive page
  src/Model/Post.php
Labels: status: awaiting author response

#1375 Feature/#1165 add docs for extensions
  docs/gatsby-config.js
  docs/source/extensions/wpgraphiql.mdx
  docs/source/extensions/wpgraphql-advanced-custom-fields.mdx
  docs/source/extensions/wpgraphql-content-blocks.mdx
  docs/source/extensions/wpgraphql-dad-jokes.mdx
  docs/source/extensions/wpgraphql-extensions.mdx
  docs/source/extensions/wpgraphql-gutenberg.mdx
  docs/source/extensions/wpgraphql-insights.mdx
  docs/source/extensions/wpgraphql-jwt-authentication.mdx
  docs/source/extensions/wpgraphql-meta-query.mdx
  docs/source/extensions/wpgraphql-seopress.mdx
  docs/source/extensions/wpgraphql-tax-query.mdx
  docs/source/extensions/wpgraphql-woocommerce.mdx
  docs/src/components/style.css
  docs/src/gatsby-theme-apollo-docs/components/template.js
Labels: Documentation

#1376 #1374 - Password Protected posts returning errors in queries for posts
  src/Model/Post.php
  tests/wpunit/PostObjectQueriesTest.php
Labels: Bug, impact: high

#1389 Feature/#1350 add filesize field to mediaitems
  src/Type/Object/MediaSize.php
  src/Type/Object/PostObject.php
  tests/wpunit/MediaItemQueriesTest.php
  wp-graphql.php
Labels: Enhancement, ObjectType: Media

#1391 Feature/#1388 filter models returned by loaders redux
  src/AppContext.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/CommentAuthorLoader.php
  src/Data/Loader/CommentLoader.php
  src/Data/Loader/MenuItemLoader.php
  src/Data/Loader/PluginLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/PostTypeLoader.php
  src/Data/Loader/TaxonomyLoader.php
  src/Data/Loader/TermObjectLoader.php
  src/Data/Loader/ThemeLoader.php
  src/Data/Loader/UserLoader.php
  src/Data/Loader/UserRoleLoader.php
  tests/wpunit/NodesTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: Bug, Component: API, Component: Connections, Component: Query, Enhancement

#1401 Allow ContentType to be returned as a possible type for homepage
  composer.lock
  src/AppContext.php
  src/Data/DataSource.php
  src/Data/NodeResolver.php
  src/Model/Post.php
  src/Model/PostType.php
  src/Model/Term.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/Object/ContentType.php
  src/Type/Object/PostObject.php
  src/Type/Object/RootQuery.php
  src/Utils/InstrumentSchema.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: Breaking Change, Component: Interfaces, Component: Query, ObjectType: Post

#1402 #1396 - location argument not properly respected for menu item queries
  src/Data/Connection/MenuItemConnectionResolver.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
Labels: Bug, impact: high

#1406 #1405 - where args missing from HierarchicalContentNode.children connections
  src/Connection/PostObjects.php
Labels: Bug, impact: high

#1407 Release/v0.11.0
  composer.lock
  docs/source/extending/connections.mdx
  docs/source/getting-started/custom-fields-and-meta.mdx
  docs/source/guides/connections.mdx
  docs/source/guides/the-graphql-query-language.mdx
  docs/src/components/style.css
  src/AppContext.php
  src/Connection/PostObjects.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Data/DataSource.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/CommentAuthorLoader.php
  src/Data/Loader/CommentLoader.php
  src/Data/Loader/MenuItemLoader.php
  src/Data/Loader/PluginLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/PostTypeLoader.php
  src/Data/Loader/TaxonomyLoader.php
  src/Data/Loader/TermObjectLoader.php
  src/Data/Loader/ThemeLoader.php
  src/Data/Loader/UserLoader.php
  src/Data/Loader/UserRoleLoader.php
  src/Data/NodeResolver.php
  src/Model/Post.php
  src/Model/PostType.php
  src/Model/Term.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/Object/ContentType.php
  src/Type/Object/MediaSize.php
  src/Type/Object/PostObject.php
  src/Type/Object/RootQuery.php
  src/Utils/InstrumentSchema.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_commands_classmap.php
  vendor/composer/autoload_commands_real.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_framework_real.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release
