Repository wp-graphql/wp-graphql, pull requests merged in 2020-03, with the labels that each got.

#1179 #1178 Invalid WP_Query parameter "ID" used in NodeResolver
  src/Data/NodeResolver.php
Labels: Bug, Component: API, Component: Interfaces, ObjectType: Post

#1187 #1186 - Comment Mutation cap check adjustment
  src/Data/CommentMutation.php
  src/Mutation/CommentDelete.php
  src/Mutation/CommentUpdate.php
Labels: Component: Mutations, ObjectType: Comment, Security, effort: low, impact: med

#1191 #1190 - orderby for search queries not working
  src/Data/Connection/PostObjectConnectionResolver.php
Labels: Bug, Component: Connections, Component: Input, impact: high

#1189 Release/v0.7.1
  .github/workflows/schema-linter.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  .travis.yml
  README.md
  bin/install-wp-tests.sh
  docs/gatsby-config.js
  docs/package.json
  docs/source/getting-started/install-and-activate.mdx
  docs/src/components/GraphiQL/style.css
  docs/src/components/Seo/index.js
  docs/src/gatsby-theme-apollo-core/utils/colors.js
  docs/src/gatsby-theme-apollo-docs/components/page-content.js
  docs/src/gatsby-theme-apollo-docs/components/page-header.js
  docs/src/gatsby-theme-apollo-docs/components/page-layout.js
  docs/src/gatsby-theme-apollo-docs/components/seo.js
  docs/src/gatsby-theme-apollo-docs/components/template.js
  docs/yarn.lock
  phpcs.xml
  src/Connection/PostObjects.php
  src/Data/CommentMutation.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/NodeResolver.php
  src/Mutation/CommentDelete.php
  src/Mutation/CommentUpdate.php
  wp-graphql.php
Labels: Release

#1197 AbstractDataLoader::get() added.
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/MenuConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
Labels: Enhancement

#1196 is_valid_model() added.
  src/Data/Connection/AbstractConnectionResolver.php
Labels: Enhancement

#1199 connection refactored
  src/Registry/TypeRegistry.php
  src/connection/README.md
  src/connection/class-comments.php
  src/connection/class-content-types.php
  src/connection/class-menu-items.php
  src/connection/class-menus.php
  src/connection/class-plugins.php
  src/connection/class-post-objects.php
  src/connection/class-revisions.php
  src/connection/class-taxonomies.php
  src/connection/class-term-objects.php
  src/connection/class-themes.php
  src/connection/class-user-roles.php
  src/connection/class-users.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_static.php
Labels: Enhancement

#1163 Release/v0.8.0
  src/Connection/Comments.php
  src/Connection/ContentTypes.php
  src/Connection/MenuItems.php
  src/Connection/Menus.php
  src/Connection/PostObjects.php
  src/Connection/Revisions.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Connection/Users.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/MenuConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Data/DataSource.php
  src/Data/Loader/CommentLoader.php
  src/Data/Loader/MenuItemLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/TermObjectLoader.php
  src/Data/Loader/UserLoader.php
  src/Model/Menu.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/HierarchicalContentNode.php
  tests/wpunit/CommentConnectionQueriesTest.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/MenuConnectionQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserObjectCursorTest.php
  tests/wpunit/UserObjectQueriesTest.php
  wp-graphql.php
Labels: Breaking Change, Component: Connections, Release, effort: high, impact: high
