Repository wp-graphql/wp-graphql, pull requests merged in 2020-05, with the labels that each got.

#1316 make PostObjectLoader.loadKeys robust against non-existent keys
  src/Data/Loader/PostObjectLoader.php
Labels: Bug, Enhancement

#1322 Fix menus not resolving with node query
  src/AppContext.php
  src/Data/DataSource.php
Labels: Bug, ObjectType: Menu, Review Ready

#1323 #1319 - Add filter to "is_graphql_http_request"
  src/Router.php
Labels: Bug

#1324 Release/v0.9.1
  src/Router.php
  wp-graphql.php
Labels: Release, Review Ready

#1327 #1326 - Use the ID even if it's encoded as a string
  src/Data/PostObjectMutation.php
Labels: Bug, impact: med
