Repository wp-graphql/wp-graphql, pull requests merged in 2020-02, with the labels that each got.

#1147 #1144 - Prevent model layer from attempting to execute cached values
  src/Model/Model.php
Labels: Bug, Security

#1149 Specify post to revision connection name to prevent clashes with unnamed user connections
  src/Connection/PostObjects.php
Labels: Breaking Change

#1156 Release/v0.6.2
  README.md
  src/Model/Model.php
  wp-graphql.php
Labels: Bug, impact: high

#1158 #1142 - Child Pages not resolving by path in NodeResolver
  src/Data/NodeResolver.php
  src/Model/Model.php
Labels: Bug, effort: low, impact: high

#1161 Release/v0.6.3
  src/Data/NodeResolver.php
  src/Model/Model.php
  wp-graphql.php
Labels: Release

#1157 Release/v0.7.0
  src/Connection/Comments.php
  src/Connection/ContentTypes.php
  src/Connection/PostObjects.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Connection/Users.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/DataSource.php
  src/Model/PostType.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/ContentTypeEnum.php
  src/Type/Enum/ContentTypeIdTypeEnum.php
  src/Type/Enum/TaxonomyIdTypeEnum.php
  src/Type/InterfaceType/HierarchicalContentNode.php
  src/Type/InterfaceType/TermNode.php
  src/Type/Object/ContentType.php
  src/Type/Object/RootQuery.php
  src/Type/Object/Taxonomy.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/TaxonomyObjectQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_framework_classmap.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1164 schema-linter, testing-integration, and wpcs workflows created.
  .github/workflows/schema-linter.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  .travis.yml
  README.md
  bin/install-wp-tests.sh
  phpcs.xml
Labels: Tests
