Repository wp-graphql/wp-graphql, pull requests merged in 2020-11, with the labels that each got.

#1551 Bug/#1437 comment database id throws errors
  src/Data/Loader/CommentLoader.php
  src/Model/Comment.php
  src/Type/Object/Comment.php
Labels: Bug, Component: Query, ObjectType: Comment

#1542 Adds externally defined post-types to ContentTypeEnum
  src/Type/Enum/ContentTypeEnum.php
Labels: Enhancement, impact: low

#1558 Phphstan
  .github/workflows/code-quality.yml
  composer.json
  composer.lock
  phpstan.neon.dist
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Model/Model.php
  src/Model/Post.php
  src/Model/Term.php
  src/Mutation/ResetUserPassword.php
  src/Mutation/TermObjectUpdate.php
  src/Type/Enum/ContentTypeEnum.php
  wp-graphql.php
Labels: Tests

#1573 Feature/#1123 make client mutation id optional for mutations
  src/Data/Cursor/CursorBuilder.php
  src/Registry/TypeRegistry.php
  wp-graphql.php
Labels: Component: Mutations

#1575 Release/v0.15.2
  docs/source/extending/resolvers.mdx
  src/Data/Cursor/CursorBuilder.php
  src/Registry/TypeRegistry.php
  wp-graphql.php
Labels: Release

#1577 WordPress.org deploy workflow
  .gitattributes
  .github/workflows/deploy-to-wordpress.yml
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.jpg
  readme.txt
Labels: Build Scripts

#1578 Release/v0.15.3
  .gitattributes
  .github/workflows/deploy-to-wordpress.yml
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.jpg
  .wordpress-org/screenshot-2.jpg
  cli/wp-cli.php
  readme.txt
  src/Admin/Settings/SettingsRegistry.php
  src/Connection/Users.php
  src/Data/CommentMutation.php
  src/Data/Config.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/DataSource.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Model/User.php
  src/Mutation/CommentCreate.php
  src/Mutation/MediaItemCreate.php
  src/Registry/TypeRegistry.php
  src/Router.php
  src/Utils/Utils.php
  vendor/autoload.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1582 Add parentId and parentDatabaseId to comment model and comment Type
  src/Model/Comment.php
  src/Type/Object/Comment.php
Labels: New Feature, ObjectType: Comment

#1583 Release/v0.15.5
  .github/workflows/testing-integration.yml
  readme.txt
  src/Model/Comment.php
  src/Type/Object/Comment.php
  wp-graphql.php
Labels: Release

#1585 v1.0
  readme.txt
  wp-graphql.php
Labels: Release

#1598 Bug/#1596 single and plural names are same
  readme.txt
  src/Registry/TypeRegistry.php
  tests/wpunit/AssertValidSchemaTest.php
  wp-graphql.php
Labels: Bug
