Repository wp-graphql/wp-graphql, pull requests merged in 2020-01, with the labels that each got.

#1102 #1101 - Updating Travis to test on PHP 7.4
  .travis.yml
  docker/docker-compose.local-app-xdebug.yml
  docker/docker-compose.local-app.yml
  docker/docker-compose.tests.yml
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Model/Post.php
  src/Type/Object/PostObject.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: Tests

#1126 Docs: Adds JWT plugins readme
  docs/source/extensions/wpgraphql-jwt-authentication.mdx
Labels: Documentation

#1122 feat: add seopress plugin to docs
  docs/gatsby-config.js
  docs/source/extensions/wpgraphql-seopress.mdx
Labels: status: awaiting author response

#1119 Merge pull request #1119 from jasonbahl/bug/#1116-ContentNode-Interface-expects-fields-that-some-types-dont-provide
  src/Type/InterfaceType/ContentNode.php
  src/Type/Object/PostObject.php
Labels: Review Ready, effort: low, impact: high, status: awaiting reviewer response

#1117 Merge pull request #1117 from wp-graphql/bug/#1115-UniformResourceIdentifiable-defines-incorrect-field-types
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/TermNode.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/Object/RootQuery.php
  src/Type/Object/User.php
Labels: Bug, Review Ready, effort: low, impact: high, status: awaiting reviewer response

#1127 #1120 - undefined index when not setting the order field for orderby
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Type/Input/PostObjectsConnectionOrderbyInput.php
Labels: Breaking Change, Bug

#1130 Adding support for GitHub Updater
  wp-graphql.php
Labels: Enhancement

#1131 #1129 - Register the NodeWithPageAttributes Interface
  package.json
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/NodeResolver.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/ContentNodeIdTypeEnum.php
  src/Type/Enum/UserNodeIdTypeEnum.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/ContentTemplate.php
  src/Type/InterfaceType/HierarchicalContentNode.php
  src/Type/InterfaceType/NodeWithAuthor.php
  src/Type/InterfaceType/NodeWithComments.php
  src/Type/InterfaceType/NodeWithContentEditor.php
  src/Type/InterfaceType/NodeWithExcerpt.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/NodeWithPageAttributes.php
  src/Type/InterfaceType/NodeWithRevisions.php
  src/Type/InterfaceType/NodeWithTitle.php
  src/Type/InterfaceType/NodeWithTrackbacks.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/Object/PostObject.php
  src/Type/Object/RootQuery.php
  src/Type/Object/SettingGroup.php
  src/Type/Object/Settings.php
  src/Type/Object/User.php
  src/Type/Union/ContentTemplateUnion.php
Labels: Bug

#1132 Release/v0.6.1
  package.json
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/NodeResolver.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/ContentNodeIdTypeEnum.php
  src/Type/Enum/UserNodeIdTypeEnum.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/ContentTemplate.php
  src/Type/InterfaceType/HierarchicalContentNode.php
  src/Type/InterfaceType/NodeWithAuthor.php
  src/Type/InterfaceType/NodeWithComments.php
  src/Type/InterfaceType/NodeWithContentEditor.php
  src/Type/InterfaceType/NodeWithExcerpt.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/NodeWithPageAttributes.php
  src/Type/InterfaceType/NodeWithRevisions.php
  src/Type/InterfaceType/NodeWithTitle.php
  src/Type/InterfaceType/NodeWithTrackbacks.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/Object/PostObject.php
  src/Type/Object/RootQuery.php
  src/Type/Object/SettingGroup.php
  src/Type/Object/Settings.php
  src/Type/Object/User.php
  src/Type/Union/ContentTemplateUnion.php
  wp-graphql.php
Labels: Release
