Repository wp-graphql/wp-graphql, pull requests merged in 2020-10, with the labels that each got.

#1485 v0.13.2
  src/Admin/Admin.php
  src/Admin/GraphiQL/GraphiQL.php
  src/Admin/Settings/Settings.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Loader/CommentLoader.php
  src/Data/PostObjectMutation.php
  src/Type/WPInterfaceType.php
  tests/wpunit/CommentConnectionQueriesTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectSearchTest.php
  tests/wpunit/UserObjectCursorTest.php
  wp-graphql.php
Labels: Release

#1498 Release v0.13.3
  src/Data/Connection/PostObjectConnectionResolver.php
  wp-graphql.php
Labels: Release

#1497 #1496 - Only apply URI interface to public Taxonomies and Post Types
  src/Type/Object/PostObject.php
  src/Type/Object/TermObject.php
Labels: Breaking Change, impact: high

#1490 #1489 - Disable Introspection Queries by default for Production and Staging
  src/Admin/Settings/Settings.php
  src/Request.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/AssertValidSchemaTest.php
Labels: Breaking Change, Component: Query, Security

#1499 #1493 - CreatePostMutation should not allow contributors to publish posts
  src/Mutation/PostObjectCreate.php
  tests/wpunit/PostObjectMutationsTest.php
Labels: Bug, Security, impact: high

#1501 #1500 - createComment mutation should not allow userId to be set as input
  src/Data/CommentMutation.php
  src/Mutation/CommentCreate.php
  tests/wpunit/CommentMutationsTest.php
Labels: Breaking Change, Bug, Security, impact: high

#1510 Make comments attached to private posts private
  src/Model/Comment.php
  src/Model/Post.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: ObjectType: Comment, Security

#1412 #1409 - Debug Log
  access-functions.php
  src/Connection/PostObjects.php
  src/Connection/TermObjects.php
  src/Data/NodeResolver.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/PostObjectUpdate.php
  src/Registry/TypeRegistry.php
  src/Request.php
  src/Type/Enum/UsersConnectionSearchColumnEnum.php
  src/Type/Union/TermObjectUnion.php
  src/Utils/DebugLog.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/AvatarObjectQueriesTest.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/DebugLogTest.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PluginObjectQueriesTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/SettingQueriesTest.php
  tests/wpunit/SettingsMutationsTest.php
  tests/wpunit/TaxonomyObjectQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/ThemeObjectQueriesTest.php
  tests/wpunit/TypesTest.php
  tests/wpunit/UserObjectMutationsTest.php
  tests/wpunit/UserObjectQueriesTest.php
  tests/wpunit/UserRoleConnectionQueriesTest.php
  tests/wpunit/UserRoleObjectQueriesTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: Component: API, Enhancement, New Feature

#1518 #1517 - fix ?graphql endpoint
  src/Router.php
Labels: Bug
