Repository wp-graphql/wp-graphql, pull requests merged in 2020-04, with the labels that each got.

#1202 Feature/1201 prevent password changed emails on user registration
  src/Mutation/UserRegister.php
  tests/wpunit/UserObjectMutationsTest.php
Labels: Component: Mutations, Enhancement, ObjectType: User, effort: low, impact: med, status: awaiting author response

#1216 #1213 - fix tests for PHP 7.4
  tests/wpunit/ModelUserTest.php
Labels: Bug, Tests, impact: med

#1232 Add description for Post Types and Taxonomies added to the Schema
  src/Type/Object/RootQuery.php
Labels: Component: API, Documentation

#1241 #1240 - Protected methods in AbstractConnectionResolver break existing plugins
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/MenuConnectionResolver.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: Bug, impact: high

#1242 Release/v0.8.3
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/MenuConnectionResolver.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
  wp-graphql.php
Labels: Release

#1249 Cleaning up the root of the project
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/testing-integration.yml
  README.md
  bin/list-mysql-containers.sh
  bin/run-docker-local-app-xdebug.sh
  bin/run-docker-local-app.sh
  bin/run-docker-test-environment-shell.sh
  bin/run-docker-test-environment.sh
  bin/run-docker-tests.sh
  docker/Dockerfile.test-base
  docker/Dockerfile.xdebug
  docker/docker-compose.local-app-xdebug.yml
  docker/docker-compose.tests.yml
Labels: Build Scripts, Documentation, Enhancement, effort: low, impact: med

#1271 #1270 - register graphql scalar
  access-functions.php
  src/Registry/TypeRegistry.php
  src/Type/WPScalar.php
  tests/wpunit/TypesTest.php
Labels: Component: API, Enhancement, Review Ready

#1275 Feature/#1274 dry up datasource
  src/AppContext.php
  src/Data/DataSource.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Type/Object/Comment.php
Labels: Enhancement
