Repository wp-graphql/wp-graphql, pull requests merged in 2021-06, with the labels that each got.

#1938 Extended connection configurations
  composer.lock
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Registry/TypeRegistry.php
  src/Utils/InstrumentSchema.php
  tests/wpunit/TypesTest.php
Labels: Enhancement

#1945 Release v1.3.10
  .github/workflows/code-quality.yml
  .github/workflows/schema-linter.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  CHANGELOG.md
  readme.txt
  src/Model/User.php
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#1951 Update GraphQL PHP to 14.8, support for Interfaces implementing Interfaces
  composer.json
  composer.lock
  src/Model/Term.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/InterfaceType/TermNode.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/TypesTest.php
Labels: Component: Interfaces

#1955 Release/v1.4.0
  .github/workflows/deploy-to-wordpress.yml
  .github/workflows/schema-linter.yml
  .github/workflows/upload-schema-artifact.yml
  CHANGELOG.md
  composer.json
  composer.lock
  docs/intro-to-graphql.md
  readme.txt
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/DataSource.php
  src/Model/Term.php
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/InterfaceType/TermNode.php
  src/Type/ObjectType/Settings.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  src/WPGraphQL.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/SettingQueriesTest.php
  tests/wpunit/SettingsQueriesTest.php
  tests/wpunit/TypesTest.php
  wp-graphql.php
Labels: Release

#1962 Release/v1.4.1
  CHANGELOG.md
  access-functions.php
  readme.txt
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  src/WPGraphQL.php
  tests/wpunit/RegisterInterfaceToTypeTest.php
  wp-graphql.php
Labels: Release

#1964 Release v1.4.2
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release
