Repository wp-graphql/wp-graphql, pull requests merged in 2021-03, with the labels that each got.

#1750 Release/v1.2.5
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#1760 Fix #1758 - Improve sizes on mediaItems to not return null when size not found
  src/Type/ObjectType/PostObject.php
  tests/_data/images/.gitignore
  tests/_data/images/test-medium.png
  tests/wpunit/MediaItemQueriesTest.php
Labels: status: awaiting author response

#1776 Release/v1.2.6
  CHANGELOG.md
  README.md
  documentation/Linting.md
  documentation/Overview.md
  documentation/Testing.md
  documentation/UsingDocker.md
  img/graphql-docs.gif
  img/intellij-php-debug-config.png
  img/intellij-php-debug-run-config.png
  img/intellij-php-servers.png
  img/intellij-php-start-debug.png
  phpcs.xml
  readme.txt
  src/Connection/MenuItems.php
  src/Connection/TermObjects.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Type/ObjectType/PostObject.php
  src/WPGraphQL.php
  tests/_data/images/.gitignore
  tests/_data/images/test-medium.png
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/PostConnectionPaginationTest.php
  tests/wpunit/PostObjectSearchTest.php
  tests/wpunit/UserConnectionPaginationTest.php
  wp-graphql.php
Labels: Release

#1781 Bug/#1780 pagitation for post in
  CHANGELOG.md
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Cursor/UserCursor.php
  tests/wpunit/CursorPaginationForPostsTest.php
  tests/wpunit/CursorPaginationForUsersTest.php
  tests/wpunit/DataConfigTest.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/PostConnectionPaginationTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectSearchTest.php
  tests/wpunit/UserConnectionPaginationTest.php
  tests/wpunit/UserObjectCursorTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: Review Ready

#1797 #1796 - Allow tests to properly set different permalink structures
  src/WPGraphQL.php
  tests/wpunit/NodeByUriTest.php
Labels: Tests

#1798 Release/v1.3.0
  .gitignore
  CHANGELOG.md
  access-functions.php
  composer.json
  composer.lock
  phpcs.xml.dist
  phpstan.neon.dist
  phpstan/class-wp-post-type.stub
  phpstan/class-wp-taxonomy.stub
  phpstan/constants.php
  readme.txt
  src/Connection/PostObjects.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Cursor/UserCursor.php
  src/Data/DataSource.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Mutation/MediaItemUpdate.php
  src/Mutation/PostObjectCreate.php
  src/Type/Enum/AvatarRatingEnum.php
  src/Type/Enum/CommentsConnectionOrderbyEnum.php
  src/Type/Enum/TaxonomyEnum.php
  src/Type/Enum/TermNodeIdTypeEnum.php
  src/Type/Enum/UsersConnectionSearchColumnEnum.php
  src/Type/Input/UsersConnectionOrderbyInput.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/ObjectType/RootQuery.php
  src/Type/Union/ContentRevisionUnion.php
  src/Type/Union/MenuItemObjectUnion.php
  src/Type/WPEnumType.php
  src/WPGraphQL.php
  tests/wpunit/CursorPaginationForPostsTest.php
  tests/wpunit/CursorPaginationForUsersTest.php
  tests/wpunit/DataConfigTest.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/PostConnectionPaginationTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectSearchTest.php
  tests/wpunit/UserConnectionPaginationTest.php
  tests/wpunit/UserObjectCursorTest.php
  tests/wpunit/UserObjectQueriesTest.php
  tests/wpunit/WPEnumTypeTest.php
  tests/wpunit/WPGraphQLTest.php
  wp-graphql.php
Labels: Release

#1800 Release/v1.3.1
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Bug, impact: high

#1801 Realease/v1.3.1
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#1805 Release/v1.3.2
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  tests/wpunit/NodeByUriTest.php
  wp-graphql.php
Labels: Release

#1809 Fixes querying child terms by URI
  src/Data/NodeResolver.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/TermObjectQueriesTest.php
Labels: Review Ready

#1812 Bug/#1810 fix regression to user connection resolver
  src/Data/Connection/UserConnectionResolver.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: Review Ready

#1815 Release/v1.3.3
  CHANGELOG.md
  readme.txt
  src/Connection/PostObjects.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/NodeResolver.php
  src/Model/CommentAuthor.php
  src/Mutation/MediaItemCreate.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/UpdateSettings.php
  src/Mutation/UserCreate.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/CommentsConnectionOrderbyEnum.php
  src/Type/Enum/ContentNodeIdTypeEnum.php
  src/Type/Enum/MenuLocationEnum.php
  src/Type/Enum/MimeTypeEnum.php
  src/Type/Enum/OrderEnum.php
  src/Type/Enum/PostObjectsConnectionDateColumnEnum.php
  src/Type/Enum/RelationEnum.php
  src/Type/Enum/TaxonomyEnum.php
  src/Type/Enum/TermObjectsConnectionOrderbyEnum.php
  src/Type/Enum/UserRoleEnum.php
  src/Type/Enum/UsersConnectionSearchColumnEnum.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/ObjectType/MediaDetails.php
  src/Type/ObjectType/MediaItemMeta.php
  src/Type/ObjectType/MediaSize.php
  src/Type/ObjectType/Menu.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/RootMutation.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/User.php
  src/Type/Union/ContentRevisionUnion.php
  src/Type/Union/PostObjectUnion.php
  src/Type/Union/TermObjectUnion.php
  src/WPGraphQL.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
  wp-graphql.php
Labels: Release
