Repository wp-graphql/wp-graphql, pull requests merged in 2021-02, with the labels that each got.

#1715 #1702 - Update Object namespace to ObjectType
  CHANGELOG.md
  bin/install-test-env.sh
  codeception.yml
  composer.lock
  readme.txt
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/ObjectType/Avatar.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/ObjectType/ContentType.php
  src/Type/ObjectType/EnqueuedScript.php
  src/Type/ObjectType/EnqueuedStylesheet.php
  src/Type/ObjectType/MediaDetails.php
  src/Type/ObjectType/MediaItemMeta.php
  src/Type/ObjectType/MediaSize.php
  src/Type/ObjectType/Menu.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/PageInfo.php
  src/Type/ObjectType/Plugin.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/PostTypeLabelDetails.php
  src/Type/ObjectType/RootMutation.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/SettingGroup.php
  src/Type/ObjectType/Settings.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/TermObject.php
  src/Type/ObjectType/Theme.php
  src/Type/ObjectType/User.php
  src/Type/ObjectType/UserRole.php
  vendor/composer/ClassLoader.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
  wp-graphql.php
Labels: Bug, impact: high

#1721 Release/v1.1.4
  CHANGELOG.md
  README.md
  access-functions.php
  bin/install-test-env.sh
  codeception.yml
  composer.lock
  phpstan.neon.dist
  readme.txt
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/ObjectType/Avatar.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/ObjectType/ContentType.php
  src/Type/ObjectType/EnqueuedScript.php
  src/Type/ObjectType/EnqueuedStylesheet.php
  src/Type/ObjectType/MediaDetails.php
  src/Type/ObjectType/MediaItemMeta.php
  src/Type/ObjectType/MediaSize.php
  src/Type/ObjectType/Menu.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/PageInfo.php
  src/Type/ObjectType/Plugin.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/PostTypeLabelDetails.php
  src/Type/ObjectType/RootMutation.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/SettingGroup.php
  src/Type/ObjectType/Settings.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/TermObject.php
  src/Type/ObjectType/Theme.php
  src/Type/ObjectType/User.php
  src/Type/ObjectType/UserRole.php
  vendor/composer/ClassLoader.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
  wp-graphql.php
Labels: Release

#1726 Release/v1.1.5
  CHANGELOG.md
  composer.json
  readme.txt
  src/Admin/Settings/SettingsRegistry.php
  src/Telemetry/Tracker.php
  src/Type/Enum/ContentTypeEnum.php
  src/WPGraphQL.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  wp-graphql.php
Labels: Release

#1730 Remove redundant CI jobs Act 2
  .github/workflows/testing-integration.yml
Labels: type: chore

#1741 #1709 - Register the DefaultTemplate Type to the Schema always
  src/Registry/TypeRegistry.php
  tests/wpunit/PostObjectQueriesTest.php
Labels: Bug, impact: high

#1742 v1.2.1
  CHANGELOG.md
  readme.txt
  src/Registry/TypeRegistry.php
  tests/wpunit/PostObjectQueriesTest.php
  wp-graphql.php
Labels: Release

#1744 v1.2.2
  .github/workflows/deploy-to-wordpress.yml
  CHANGELOG.md
  readme.txt
  wp-graphql.php
Labels: Release

#1745 v1.2.3
  .distignore
  CHANGELOG.md
  readme.txt
  wp-graphql.php
Labels: Release

#1746 Release/v1.2.4
  .distignore
  .github/workflows/deploy-to-wordpress.yml
  CHANGELOG.md
  readme.txt
  wp-graphql.php
Labels: Release, impact: high
