Repository wp-graphql/wp-graphql, pull requests merged in 2021-07, with the labels that each got.

#1982 Release/v1.5.0
  .env.dist
  .github/workflows/deploy-docker-image.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  access-functions.php
  bin/install-test-env.sh
  bin/run-docker.sh
  codeception.dist.yml
  composer.json
  composer.lock
  deactivation.php
  docker-compose.yml
  docker/app.Dockerfile
  docker/app.entrypoint.sh
  docker/app.post-setup.sh
  docker/app.setup.sh
  docker/testing.Dockerfile
  docker/testing.entrypoint.sh
  readme.txt
  src/Connection/PostObjects.php
  src/Connection/TermObjects.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/ContentTypeEnum.php
  src/Type/ObjectType/MenuItem.php
  src/Utils/InstrumentSchema.php
  src/WPGraphQL.php
  tests/wpunit/AssertValidSchemaTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  wp-graphql.php
Labels: Release

#1984 PHP 8 support
  .env.dist
  .github/workflows/testing-integration.yml
  composer.json
  composer.lock
  docker/app.Dockerfile
  docker/testing.Dockerfile
  docker/testing.entrypoint.sh
  tests/wpunit/TypesTest.php
Labels: Build Scripts, Enhancement, php

#1990 Add isContentNode and isTermNode fields
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/TermNode.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Utils/Preview.php
  tests/wpunit/NodeByUriTest.php
Labels: Component: Interfaces, Component: Query, Enhancement

#1991 Release v1.5.1
  .env.dist
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  composer.json
  composer.lock
  docker/app.Dockerfile
  docker/testing.Dockerfile
  docker/testing.entrypoint.sh
  docs/connections.md
  readme.txt
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/TermNode.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Utils/Preview.php
  src/WPGraphQL.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/TypesTest.php
  wp-graphql.php
Labels: Release

#1992 Fix conflict with AmpWP plugin
  src/Data/NodeResolver.php
  tests/wpunit/PluginCompatibilityTest.php
Labels: Extensions

#2001 Use mariadb instead of mysql for tests
  docker-compose.yml
Labels: Build Scripts, Tests

#2009 Refactor TypeRegistry->register_connection() into it's own class
  src/Registry/TypeRegistry.php
  src/Type/WPConnectionType.php
Labels: Architecture, Component: API, Component: Connections, Enhancement, code quality

#2013 Release v1.5.3
  .github/workflows/deploy-docker-image.yml
  CHANGELOG.md
  docker-compose.yml
  docker/testing.Dockerfile
  docker/testing.entrypoint.sh
  docs/concepts.md
  readme.txt
  src/Registry/TypeRegistry.php
  src/Type/WPConnectionType.php
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2012 - Add acceptance and functional tests back to the Github Workflow
  .github/workflows/testing-integration.yml
  docker/app.post-setup.sh
  docker/testing.entrypoint.sh
  tests/functional/ApolloPreflightRequestCept.php
  tests/functional/BasicPostListCept.php
  tests/functional/BatchQueriesCept.php
  tests/functional/BatchQueriesDisabledCept.php
  tests/functional/MenuWithMenuItemsCept.php
  tests/functional/PostListWithDifferentStatusCept.php
  tests/functional/QueryDepthRuleCept.php
  tests/functional/RestrictedQueriesCept.php
Labels: Build Scripts, Tests

#2011 #1947 - let objects/interfaces register connections
  .github/workflows/testing-integration.yml
  access-functions.php
  src/Connection/Commenter.php
  src/Connection/ContentTypes.php
  src/Connection/EnqueuedScripts.php
  src/Connection/EnqueuedStylesheets.php
  src/Connection/MediaItems.php
  src/Connection/MenuItemLinkableConnection.php
  src/Connection/Menus.php
  src/Connection/Plugins.php
  src/Connection/Themes.php
  src/Connection/UserRoles.php
  src/Connection/Users.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/TermNode.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/User.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  tests/wpunit/ConnectionRegistrationTest.php
  tests/wpunit/RootQueryConnectionsTest.php
Labels: Component: API, Component: Connections

#2021 Release v1.5.4
  .github/workflows/deploy-docker-image.yml
  .github/workflows/schema-linter.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  access-functions.php
  docker/app.post-setup.sh
  docker/testing.entrypoint.sh
  readme.txt
  src/Connection/Commenter.php
  src/Connection/ContentTypes.php
  src/Connection/EnqueuedScripts.php
  src/Connection/EnqueuedStylesheets.php
  src/Connection/MediaItems.php
  src/Connection/MenuItemLinkableConnection.php
  src/Connection/Menus.php
  src/Connection/Plugins.php
  src/Connection/Themes.php
  src/Connection/UserRoles.php
  src/Connection/Users.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/TermNode.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/User.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/WPGraphQL.php
  tests/functional/ApolloPreflightRequestCept.php
  tests/functional/BasicPostListCept.php
  tests/functional/BatchQueriesCept.php
  tests/functional/BatchQueriesDisabledCept.php
  tests/functional/MenuWithMenuItemsCept.php
  tests/functional/PostListWithDifferentStatusCept.php
  tests/functional/QueryDepthRuleCept.php
  tests/functional/RestrictedQueriesCept.php
  tests/wpunit/ConnectionRegistrationTest.php
  tests/wpunit/RootQueryConnectionsTest.php
  wp-graphql.php
Labels: Release

#2025 Update tests to use WordPress 5.8
  .github/workflows/testing-integration.yml
  readme.txt
Labels: Build Scripts, Tests

#2029 Release v1.5.5
  .github/workflows/deploy-docker-image.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  docker/app.setup.sh
  docker/testing.Dockerfile
  readme.txt
  src/WPGraphQL.php
  tests/_bootstrap/bootstrap.php
  tests/_data/config.php
  tests/functional.suite.dist.yml
  tests/functional/ApolloPreflightRequestCept.php
  tests/functional/BasicPostListCept.php
  tests/functional/BatchQueriesCept.php
  tests/functional/BatchQueriesDisabledCept.php
  tests/functional/MenuWithMenuItemsCept.php
  tests/functional/PostListWithDifferentStatusCept.php
  tests/functional/QueryDepthRuleCept.php
  tests/functional/RestrictedQueriesCept.php
  tests/functional/bootstrap.php
  wp-graphql.php
Labels: Release

#2031 Fix negative performance with Post / User model
  .codeclimate.yml
  src/Data/Loader/UserLoader.php
  src/Model/User.php
  src/Mutation/ResetUserPassword.php
  src/Mutation/SendPasswordResetEmail.php
  src/Mutation/UserCreate.php
  src/Mutation/UserDelete.php
  src/Mutation/UserRegister.php
  src/Mutation/UserUpdate.php
  tests/wpunit/UserObjectMutationsTest.php
Labels: Component: Model Layer, Component: Query, ObjectType: Post, ObjectType: User, performance

#2000 Fix lazy-loading types
  access-functions.php
  src/Registry/TypeRegistry.php
  src/Type/Input/MenuItemsConnectionWhereArgs.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/WPConnectionType.php
  src/Type/WPInputObjectType.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  src/WPGraphQL.php
  tests/wpunit/AssertValidSchemaTest.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/MenuConnectionQueriesTest.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/PostObjectNestedMutationsTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/PreresolveTest.php
  tests/wpunit/RequestTest.php
  tests/wpunit/TaxonomyObjectQueriesTest.php
  tests/wpunit/TermObjectMutationsTest.php
  tests/wpunit/UserObjectMutationsTest.php
  tests/wpunit/ViewerQueryTest.php
  tests/wpunit/WPGraphQLTest.php
Labels: Needs Discussion, performance

#2035 Fix variables sent to `after_execute_actions`
  src/Request.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  tests/wpunit/FiltersTest.php
Labels: Bug, Component: API

#2036 Release/v1.5.6
  CHANGELOG.md
  readme.txt
  src/Request.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/FiltersTest.php
  wp-graphql.php
Labels: Release

#2038 Ingore docs in deployed code
  .distignore
  composer.json
Labels: Build Scripts

#2039 Release/v1.5.8
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2040 Release/v1.5.8
  .distignore
  CHANGELOG.md
  composer.json
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2032 Release/v1.6.0
  .codeclimate.yml
  CHANGELOG.md
  access-functions.php
  readme.txt
  src/Data/Loader/UserLoader.php
  src/Model/User.php
  src/Mutation/ResetUserPassword.php
  src/Mutation/SendPasswordResetEmail.php
  src/Mutation/UserCreate.php
  src/Mutation/UserDelete.php
  src/Mutation/UserRegister.php
  src/Mutation/UserUpdate.php
  src/Registry/TypeRegistry.php
  src/Type/Input/MenuItemsConnectionWhereArgs.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/WPConnectionType.php
  src/Type/WPInputObjectType.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/InstrumentSchema.php
  src/WPGraphQL.php
  tests/wpunit/AssertValidSchemaTest.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/MenuConnectionQueriesTest.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/PostObjectNestedMutationsTest.php
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/PreresolveTest.php
  tests/wpunit/RequestTest.php
  tests/wpunit/TaxonomyObjectQueriesTest.php
  tests/wpunit/TermObjectMutationsTest.php
  tests/wpunit/UserObjectMutationsTest.php
  tests/wpunit/ViewerQueryTest.php
  tests/wpunit/WPGraphQLTest.php
  wp-graphql.php
Labels: Release, impact: high, performance

#2043 Bug/#2042
  CHANGELOG.md
  readme.txt
  src/Request.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/FiltersTest.php
  wp-graphql.php
Labels: Bug, Gatsby, Regression, impact: high

#2045 Release/v1.6.1
  CHANGELOG.md
  readme.txt
  src/Request.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/FiltersTest.php
  wp-graphql.php
Labels: Release
