Repository wp-graphql/wp-graphql, pull requests merged in 2022-06, with the labels that each got.

#2386 Feat/add get home url helper
  src/Data/NodeResolver.php
  src/Model/MenuItem.php
  src/Model/Post.php
  src/Model/PostType.php
  src/Model/Term.php
  src/Model/User.php
  src/Utils/Utils.php
  tests/wpunit/SettingsMutationsTest.php
  tests/wpunit/UtilsTest.php
Labels: Enhancement, Ready for Review, Component: API

#2388 Feat: query `menu` by `SLUG` and `LOCATION`.
  src/Type/Enum/MenuNodeIdTypeEnum.php
  src/Type/ObjectType/RootQuery.php
  tests/wpunit/MenuQueriesTest.php
Labels: Enhancement, Ready for Review, Component: Query, ObjectType: Menu

#2406 chore: update PHPUnit, WPBrowser, and WPGraphQL Test Case
  composer.json
  composer.lock
  tests/wpunit/FiltersTest.php
  tests/wpunit/PluginCompatibilityTest.php
  tests/wpunit/RootQueryConnectionsTest.php
  tests/wpunit/TypesTest.php
  tests/wpunit/UserObjectMutationsTest.php
Labels: Tests, Ready for Review, dependencies

#2360 Chore: PHPStan 1.6 fixes (first pass)
  deactivation.php
  phpstan.neon.dist
  phpstan/class-wp-dependency.stub
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/EnqueuedScriptLoader.php
  src/Data/Loader/TermObjectLoader.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Model/MenuItem.php
  src/Model/Model.php
  src/Model/User.php
  src/Registry/SchemaRegistry.php
  src/Registry/TypeRegistry.php
  src/Request.php
  src/Router.php
  src/Server/ValidationRules/RequireAuthentication.php
  src/Type/WPInputObjectType.php
  src/Utils/DebugLog.php
  src/Utils/InstrumentSchema.php
  src/Utils/Preview.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  src/WPSchema.php
Labels: Ready for Review, status: awaiting reviewer response, type: chore, code quality

#2361 Chore: PHPStan 1.6 fixes (secondpass)
  .github/workflows/code-quality.yml
  access-functions.php
  composer.json
  composer.lock
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/DataSource.php
  src/Data/Loader/CommentLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/TermObjectLoader.php
  src/Data/NodeResolver.php
  src/Model/Avatar.php
  src/Model/Comment.php
  src/Model/MenuItem.php
  src/Model/Post.php
  src/Model/Term.php
  src/Model/User.php
  src/Mutation/MediaItemCreate.php
  src/Mutation/MediaItemDelete.php
  src/Mutation/MediaItemUpdate.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/PostObjectDelete.php
  src/Mutation/PostObjectUpdate.php
  src/Request.php
  src/Server/ValidationRules/QueryDepth.php
  src/Type/Enum/MediaItemSizeEnum.php
  src/Type/Enum/MediaItemStatusEnum.php
  src/Type/Enum/TimezoneEnum.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/ObjectType/EnqueuedScript.php
  src/Type/ObjectType/EnqueuedStylesheet.php
  src/Type/ObjectType/MediaSize.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/Settings.php
  src/Type/ObjectType/User.php
  src/Type/Union/ContentRevisionUnion.php
  src/Type/WPConnectionType.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/AvatarObjectQueriesTest.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: Ready for Review, status: awaiting reviewer response, php, code quality

#2411 Bug/#2409 menu item locations conflicts with taxonomy location
  .github/workflows/schema-linter.yml
  composer.json
  composer.lock
  src/Data/Connection/MenuItemConnectionResolver.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
Labels: Bug, ObjectType: Menu

#2412 - update tests to run in php 8.1 with WP 6.0
  .github/workflows/deploy-docker-image.yml
  .github/workflows/testing-integration.yml
Labels: Build Scripts

#2417 Release v1.8.4
  CHANGELOG.md
  package.json
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2422 Hotfix/fix typehint for tracing callback
  src/Request.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/TracingTest.php
Labels: Regression

#2424 Release/v1.8.5
  CHANGELOG.md
  package.json
  readme.txt
  src/Request.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/TracingTest.php
  wp-graphql.php
Labels: Release

#2428 Release v1.8.6
  CHANGELOG.md
  package.json
  readme.txt
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/TracingTest.php
  wp-graphql.php
Labels: Release
