Repository wp-graphql/wp-graphql, pull requests merged in 2022-07, with the labels that each got.

#2440 Bug/#2439 dependabot updates
  CHANGELOG.md
  build/app.asset.php
  build/app.css
  build/app.js
  build/graphiqlAuthSwitch.asset.php
  build/graphiqlAuthSwitch.js
  build/graphiqlFullscreenToggle.asset.php
  build/graphiqlQueryComposer.asset.php
  build/graphiqlQueryComposer.js
  build/index.asset.php
  build/index.js
  package-lock.json
  package.json
  packages/wpgraphiql/components/Router/Router.js
  packages/wpgraphiql/components/Router/Router.test.js
  packages/wpgraphiql/screens/GraphiQL/components/GrapiQLToolbar.test.js
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
  yarn.lock
Labels: dependencies, javascript

#2442 fix: contentNodes field is not available for custom taxonomies #2441
  src/Connection/PostObjects.php
  tests/wpunit/TermNodeTest.php
Labels: Bug, Ready for Review, ObjectType: Term

#2449 Release/v1.8.7
  CHANGELOG.md
  build/app.asset.php
  build/app.css
  build/app.js
  build/graphiqlAuthSwitch.asset.php
  build/graphiqlAuthSwitch.js
  build/graphiqlFullscreenToggle.asset.php
  build/graphiqlQueryComposer.asset.php
  build/graphiqlQueryComposer.js
  build/index.asset.php
  build/index.js
  package-lock.json
  package.json
  packages/wpgraphiql/components/Router/Router.js
  packages/wpgraphiql/components/Router/Router.test.js
  packages/wpgraphiql/screens/GraphiQL/components/GrapiQLToolbar.test.js
  readme.txt
  src/Connection/PostObjects.php
  src/Request.php
  src/WPGraphQL.php
  tests/wpunit/TermNodeTest.php
  wp-graphql.php
  yarn.lock
Labels: Release

#2450 Chore:fix PHPCompatibilityWP lint config
  phpcs.xml.dist
  src/Data/Connection/PluginConnectionResolver.php
Labels: Bug, Ready for Review

#2453 chore: build deps for PHP 7.3
  .github/workflows/code-quality.yml
  .github/workflows/wordpress-coding-standards.yml
  composer.json
  composer.lock
  docs/testing.md
Labels: Ready for Review, dependencies

#2454 ci: add linter to ensure PR titles adhere to conventional commit standards
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint-pr.yml
Labels: Build Scripts

#2452 fix: #2448 - Fixes Comment.author connection resolver to properly load both User and CommentAuthor types
  src/Model/Comment.php
  src/Type/ObjectType/Comment.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: ObjectType: Comment
