Repository wp-graphql/wp-graphql, pull requests merged in 2022-03, with the labels that each got.

#2265 Feature/add appsero tracking
  .github/workflows/graphiql-unit-tests.yml
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  phpstan.neon.dist
  phpstan/constants.php
  readme.txt
  wp-graphql.php
Labels: Enhancement

#2276 #2274 - fix bug with the generalSettings.url field being removed
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
Labels: Review Ready

#2278 Add composer post-install script
  .gitattributes
  composer.json
Labels: Build Scripts

#2279 Release/v1.7.2
  .gitattributes
  .github/workflows/deploy-to-wordpress.yml
  .github/workflows/graphiql-e2e-tests.yml
  .github/workflows/graphiql-unit-tests.yml
  CHANGELOG.md
  composer.json
  docker/app.post-setup.sh
  docker/testing.entrypoint.sh
  package.json
  readme.txt
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2286 Remove old GraphiQL JavaScript
  codeception.dist.yml
  composer.json
  docs/authentication.md
  docs/security.md
  src/Admin/GraphiQL/app/.gitignore
  src/Admin/GraphiQL/app/README.md
  src/Admin/GraphiQL/app/build/asset-manifest.json
  src/Admin/GraphiQL/app/build/index.html
  src/Admin/GraphiQL/app/build/static/css/2.8d9709c7.chunk.css
  src/Admin/GraphiQL/app/build/static/css/2.8d9709c7.chunk.css.map
  src/Admin/GraphiQL/app/build/static/css/main.6f63d9ad.chunk.css
  src/Admin/GraphiQL/app/build/static/css/main.6f63d9ad.chunk.css.map
  src/Admin/GraphiQL/app/build/static/js/2.218c6839.chunk.js
  src/Admin/GraphiQL/app/build/static/js/2.218c6839.chunk.js.LICENSE.txt
  src/Admin/GraphiQL/app/build/static/js/2.218c6839.chunk.js.map
  src/Admin/GraphiQL/app/build/static/js/main.97617add.chunk.js
  src/Admin/GraphiQL/app/build/static/js/main.97617add.chunk.js.map
  src/Admin/GraphiQL/app/build/static/js/runtime-main.f6d70c77.js
  src/Admin/GraphiQL/app/build/static/js/runtime-main.f6d70c77.js.map
  src/Admin/GraphiQL/app/package.json
  src/Admin/GraphiQL/app/public/index.html
  src/Admin/GraphiQL/app/src/App.js
  src/Admin/GraphiQL/app/src/app.css
  src/Admin/GraphiQL/app/src/index.js
  src/Admin/GraphiQL/app/src/snippets.js
  src/Admin/GraphiQL/app/yarn.lock
  src/Admin/GraphiQL/js/graphiql-helpers.js
Labels: Build Scripts, javascript

#2296 Register post/page templates with get_page_templates()
  src/Model/Post.php
  src/Registry/TypeRegistry.php
  src/Type/InterfaceType/ContentTemplate.php
Labels: Enhancement, status: awaiting reviewer response, ObjectType: Post, php

#2295 fix: `menus` should return empty when `location` doesn't have a menu assigned.
  src/Data/Connection/MenuConnectionResolver.php
  tests/wpunit/MenuConnectionQueriesTest.php
Labels: Bug, status: awaiting reviewer response, ObjectType: Menu, php
