Repository wp-graphql/wp-graphql, pull requests merged in 2022-11, with the labels that each got.

#2581 feat: support deprecation reason on connections
  src/Type/WPConnectionType.php
Labels: needs: tests

#2582 fix(noderesolver): adding extra_query_vars in graphql_pre_resolve_uri…
  src/Data/NodeResolver.php
Labels: type: enhancement, status: in review, scope: API, Component: Query

#2541 feat: Obfuscate `SendPasswordResetEmail` response.
  src/Mutation/SendPasswordResetEmail.php
  tests/wpunit/UserObjectMutationsTest.php
Labels: type: enhancement, status: in review, scope: security, Component: Mutations, ObjectType: User

#2544 chore: log and cleanup deprecations
  src/AppContext.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Cursor/CommentObjectCursor.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Cursor/TermObjectCursor.php
  src/Data/Cursor/UserCursor.php
  src/Data/DataSource.php
  src/Data/Loader/AbstractDataLoader.php
  src/Router.php
  src/Type/Union/MenuItemObjectUnion.php
  src/Types.php
  src/WPGraphQL.php
Labels: type: enhancement, scope: code quality

#2605 chore: bump tested WP version to v6.1
  .github/workflows/code-quality.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  bin/run-docker.sh
  docker-compose.yml
  docs/testing.md
  readme.txt
  wp-graphql.php
Labels: type: chore

#2611 release: v1.12.2
  .github/workflows/code-quality.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
  CHANGELOG.md
  bin/run-docker.sh
  docker-compose.yml
  docs/testing.md
  package-lock.json
  readme.txt
  src/AppContext.php
  src/Connection/Users.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Cursor/CommentObjectCursor.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Cursor/TermObjectCursor.php
  src/Data/Cursor/UserCursor.php
  src/Data/DataSource.php
  src/Data/Loader/AbstractDataLoader.php
  src/Mutation/SendPasswordResetEmail.php
  src/Router.php
  src/Type/Union/MenuItemObjectUnion.php
  src/Types.php
  src/WPGraphQL.php
  tests/wpunit/UserObjectMutationsTest.php
  wp-graphql.php
Labels: Release

#2540 fix: deprecate Comment `approved` field in favor of `status: CommentStatusEnum`
  src/Data/CommentMutation.php
  src/Model/Comment.php
  src/Mutation/CommentCreate.php
  src/Registry/TypeRegistry.php
  src/Type/Enum/CommentStatusEnum.php
  src/Type/Enum/CommentsConnectionOrderbyEnum.php
  src/Type/ObjectType/Comment.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: type: bug, status: in review, ObjectType: Comment

#2557 feat: Add `deregister_graphql_type()` access function and corresponding `graphql_excluded_types` filter.
  access-functions.php
  src/Registry/TypeRegistry.php
  src/Type/WPConnectionType.php
  src/Type/WPUnionType.php
  tests/wpunit/AccessFunctionsTest.php
Labels: type: enhancement, status: in review, scope: API

#2626 release: v1.13.1
  CHANGELOG.md
  readme.txt
  src/Registry/TypeRegistry.php
  src/Type/WPMutationType.php
  src/WPGraphQL.php
  tests/wpunit/AccessFunctionsTest.php
  wp-graphql.php
Labels: Release

#2632 release: v1.13.2
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2636 release: v1.13.3
  CHANGELOG.md
  readme.txt
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release

#2637 release: v1.13.4
  CHANGELOG.md
  readme.txt
  src/Connection/Comments.php
  src/Connection/MenuItems.php
  src/Connection/PostObjects.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Connection/Users.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Type/Connection/Comments.php
  src/Type/Connection/MenuItems.php
  src/Type/Connection/PostObjects.php
  src/Type/Connection/Taxonomies.php
  src/Type/Connection/TermObjects.php
  src/Type/Connection/Users.php
  src/Type/InterfaceType/CommentConnection.php
  src/Type/InterfaceType/ContentNode.php
  src/Type/InterfaceType/ContentNodeConnection.php
  src/Type/InterfaceType/ContentTypeConnection.php
  src/Type/InterfaceType/MenuConnection.php
  src/Type/InterfaceType/MenuItemConnection.php
  src/Type/InterfaceType/MenuItemLinkableConnection.php
  src/Type/InterfaceType/TaxonomyConnection.php
  src/Type/InterfaceType/TermNodeConnection.php
  src/Type/InterfaceType/UserConnection.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/User.php
  src/Type/WPConnectionType.php
  src/WPGraphQL.php
  tests/wpunit/ConnectionInterfaceTest.php
  wp-graphql.php
Labels: Release
