Repository wp-graphql/wp-graphql, pull requests merged in 2022-09, with the labels that each got.

#2503 ci: enable codeception debugging via GH Actions
  .github/workflows/testing-integration.yml
Labels: Tests, Ready for Review, type: chore

#2502 feat: add `idType` arg to `RootQuery.comment`
  src/Registry/TypeRegistry.php
  src/Type/Enum/CommentNodeIdTypeEnum.php
  src/Type/ObjectType/RootQuery.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: Enhancement, Ready for Review, ObjectType: Comment, Component: Query

#2499 fix: check for multiple theme capabilities on Theme::is_private()
  src/Model/Theme.php
  tests/wpunit/ThemeObjectQueriesTest.php
Labels: Bug, Ready for Review, Security, Component: Model Layer

#2498 feat: add `include` and `exclude` args to `MediaDetails.sizes`
  src/Type/ObjectType/MediaDetails.php
  tests/wpunit/MediaItemQueriesTest.php
Labels: Enhancement, Ready for Review, Component: Query, ObjectType: Media, performance

#2506 fix: specify when `id` arg takes an (int) database ID
  src/Connection/MenuItems.php
  src/Connection/PostObjects.php
  src/Type/ObjectType/RootQuery.php
Labels: Enhancement, Ready for Review, Component: Input

#2504 fix: filter `mediaItems` query by `mimeType`
  src/Data/Connection/PostObjectConnectionResolver.php
  tests/wpunit/MediaItemQueriesTest.php
Labels: Bug, Ready for Review, Component: Query, ObjectType: Media

#2505 feat: login user after successful `resetUserPassword` mutation
  src/Mutation/ResetUserPassword.php
  tests/wpunit/UserObjectMutationsTest.php
Labels: Enhancement, Ready for Review, Security, Component: Mutations, ObjectType: User

#2510 release: v1.10.0
  .github/stale.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  composer.json
  composer.lock
  docs/authentication.md
  phpcs.xml.dist
  readme.txt
  src/Admin/Settings/Settings.php
  src/Admin/Settings/SettingsRegistry.php
  src/Connection/MenuItems.php
  src/Connection/PostObjects.php
  src/Connection/TermObjects.php
  src/Connection/Users.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/DataSource.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Data/TermObjectMutation.php
  src/Model/Post.php
  src/Model/Theme.php
  src/Mutation/ResetUserPassword.php
  src/Mutation/SendPasswordResetEmail.php
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
  src/Router.php
  src/Type/Enum/CommentNodeIdTypeEnum.php
  src/Type/Enum/MediaItemSizeEnum.php
  src/Type/InterfaceType/ContentTemplate.php
  src/Type/ObjectType/MediaDetails.php
  src/Type/ObjectType/RootQuery.php
  src/WPGraphQL.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/PageByUriTest.php
  tests/wpunit/ThemeObjectQueriesTest.php
  tests/wpunit/UserObjectMutationsTest.php
  wp-graphql.php
Labels: Release

#2519 feat: Add QueryAnalyzer and Expose "X-GraphQL-Keys" in headers
  access-functions.php
  src/Mutation/MediaItemUpdate.php
  src/Request.php
  src/Router.php
  src/Type/ObjectType/Avatar.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/ObjectType/ContentType.php
  src/Type/ObjectType/Menu.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/Plugin.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/TermObject.php
  src/Type/ObjectType/Theme.php
  src/Type/ObjectType/User.php
  src/Type/ObjectType/UserRole.php
  src/Type/WPUnionType.php
  src/Utils/QueryAnalyzer.php
  src/Utils/Utils.php
  src/WPGraphQL.php
  tests/functional/GraphQLHeadersCept.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/QueryAnalyzerTest.php
  tests/wpunit/UtilsTest.php
Labels: Enhancement

#2521 chore: refactor `AbstractConnectionResolver::$args` handling
  src/Data/Connection/AbstractConnectionResolver.php
Labels: Enhancement, Ready for Review, Component: Connections, Component: API

#2522 feat: allow global/database IDs in Comment connection where args `ID` inputs
  src/Connection/Comments.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  tests/wpunit/CommentConnectionQueriesTest.php
Labels: Enhancement, Ready for Review, Component: Connections, ObjectType: Comment

#2526 fix: ensure responses in QueryAnalyzer are unique
  src/Request.php
  src/Utils/QueryAnalyzer.php
Labels: Enhancement

#2527 release: v1.11.0
  CHANGELOG.md
  access-functions.php
  readme.txt
  src/Connection/Comments.php
  src/Connection/MenuItems.php
  src/Connection/PostObjects.php
  src/Connection/TermObjects.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Mutation/MediaItemUpdate.php
  src/Request.php
  src/Router.php
  src/Type/ObjectType/Avatar.php
  src/Type/ObjectType/Comment.php
  src/Type/ObjectType/CommentAuthor.php
  src/Type/ObjectType/ContentType.php
  src/Type/ObjectType/Menu.php
  src/Type/ObjectType/MenuItem.php
  src/Type/ObjectType/Plugin.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/Taxonomy.php
  src/Type/ObjectType/TermObject.php
  src/Type/ObjectType/Theme.php
  src/Type/ObjectType/User.php
  src/Type/ObjectType/UserRole.php
  src/Type/WPUnionType.php
  src/Utils/QueryAnalyzer.php
  src/Utils/Utils.php
  src/WPGraphQL.php
  tests/functional/GraphQLHeadersCept.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/CommentConnectionQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/QueryAnalyzerTest.php
  tests/wpunit/TermObjectConnectionQueriesTest.php
  tests/wpunit/UtilsTest.php
  wp-graphql.php
Labels: Release

#2533 release: v1.11.1
  CHANGELOG.md
  readme.txt
  src/Data/Connection/MenuItemConnectionResolver.php
  src/WPGraphQL.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  wp-graphql.php
Labels: Release

#2552 release: v1.11.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  readme.txt
  src/Admin/GraphiQL/GraphiQL.php
  src/Utils/QueryAnalyzer.php
  src/WPGraphQL.php
  wp-graphql.php
Labels: Release
