Repository wp-graphql/wp-graphql, pull requests merged in 2022-10, with the labels that each got.

#2399 feat: schema customization with post type args
  docs/custom-post-types.md
  docs/custom-taxonomies.md
  phpstan/class-wp-post-type.stub
  phpstan/class-wp-taxonomy.stub
  src/Connection/Comments.php
  src/Connection/PostObjects.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Type/InterfaceType/EnqueuedAsset.php
  src/Type/InterfaceType/NodeWithAuthor.php
  src/Type/InterfaceType/NodeWithComments.php
  src/Type/InterfaceType/NodeWithContentEditor.php
  src/Type/InterfaceType/NodeWithExcerpt.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/NodeWithPageAttributes.php
  src/Type/InterfaceType/NodeWithRevisions.php
  src/Type/InterfaceType/NodeWithTemplate.php
  src/Type/InterfaceType/NodeWithTitle.php
  src/Type/InterfaceType/NodeWithTrackbacks.php
  src/Type/InterfaceType/TermNode.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/TermObject.php
  src/Type/Union/MenuItemObjectUnion.php
  src/Type/Union/PostObjectUnion.php
  src/Type/Union/TermObjectUnion.php
  src/WPGraphQL.php
  tests/wpunit.suite.dist.yml
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
Labels: type: enhancement, status: in review, needs: reviewer response, scope: API, compat: possible break

#2556 chore: use ENV variables for installing WordPress test environment
  bin/install-test-env.sh
Labels: type: enhancement, status: in review, scope: build scripts

#2573 fix: (phpstan) check if wp_parse_url() returns array
  src/Registry/Utils/TermObject.php
Labels: type: bug, scope: code quality

#2574 chore: cleanup and update version tags
  access-functions.php
  package.json
  src/Connection/TermObjects.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/TermObject.php
  src/WPGraphQL.php
Labels: type: chore, scope: code quality

#2566 release: v1.12.0
  CHANGELOG.md
  access-functions.php
  bin/install-test-env.sh
  build/graphiqlQueryComposer.asset.php
  build/graphiqlQueryComposer.js
  composer.json
  composer.lock
  docs/custom-post-types.md
  docs/custom-taxonomies.md
  docs/intro-to-graphql.md
  package-lock.json
  package.json
  packages/README.md
  packages/graphiql-query-composer/components/FieldView.js
  phpstan.neon.dist
  phpstan/class-wp-post-type.stub
  phpstan/class-wp-taxonomy.stub
  readme.txt
  src/Admin/GraphiQL/GraphiQL.php
  src/Connection/Comments.php
  src/Connection/PostObjects.php
  src/Connection/Taxonomies.php
  src/Connection/TermObjects.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/NodeResolver.php
  src/Model/MenuItem.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Router.php
  src/Type/Enum/TimezoneEnum.php
  src/Type/InterfaceType/EnqueuedAsset.php
  src/Type/InterfaceType/NodeWithAuthor.php
  src/Type/InterfaceType/NodeWithComments.php
  src/Type/InterfaceType/NodeWithContentEditor.php
  src/Type/InterfaceType/NodeWithExcerpt.php
  src/Type/InterfaceType/NodeWithFeaturedImage.php
  src/Type/InterfaceType/NodeWithPageAttributes.php
  src/Type/InterfaceType/NodeWithRevisions.php
  src/Type/InterfaceType/NodeWithTemplate.php
  src/Type/InterfaceType/NodeWithTitle.php
  src/Type/InterfaceType/NodeWithTrackbacks.php
  src/Type/InterfaceType/TermNode.php
  src/Type/InterfaceType/UniformResourceIdentifiable.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/TermObject.php
  src/Type/Union/MenuItemObjectUnion.php
  src/Type/Union/PostObjectUnion.php
  src/Type/Union/TermObjectUnion.php
  src/WPGraphQL.php
  tests/functional/GraphQLHeadersCept.php
  tests/wpunit.suite.dist.yml
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  tests/wpunit/UserObjectMutationsTest.php
  wp-graphql.php
Labels: Release

#2590 fix: Add list of node types as X-GraphQL-Keys instead of list of edge types
  src/Utils/QueryAnalyzer.php
  tests/functional/GraphQLHeadersCept.php
Labels: needs: tests
