Repository wp-graphql/wp-graphql, pull requests merged in 2023-10, with the labels that each got.

#2341 fix: Wrong term URIs for subsites
  src/Model/Term.php
  src/Registry/Utils/TermObject.php
Labels: type: bug, stale?, status: awaiting author response, ObjectType: Term, Component: Query, Component: Multisite

#2944 fix: skip setting if no `$setting['group']`
  src/Data/DataSource.php
  tests/wpunit/SettingQueriesTest.php
Labels: type: bug, status: in review, ObjectType: Settings

#2955 test: backfill `register_graphql_input|union_type()` tests
  tests/wpunit/AccessFunctionsTest.php
Labels: scope: tests, status: in review, type: chore

#2953 fix: term uri, early return
  src/Model/Term.php
  src/Registry/Utils/TermObject.php
Labels: type: enhancement

#2949 fix: correctly get `default` user role for settings selectbox
  src/Admin/Settings/SettingsRegistry.php
  tests/functional/GraphqlSettingsPageCept.php
Labels: type: bug, status: in review, needs: tests

#2945 fix: rename fields registered by connections when using `rename_graphql_field()`
  access-functions.php
  src/Type/WPConnectionType.php
  tests/wpunit/AccessFunctionsTest.php
Labels: type: bug, status: in review, needs: reviewer response, scope: API

#2959 chore: remove @phpstan-ignore annotations
  phpstan/constants.php
  wp-graphql.php
Labels: status: in review, type: chore

#2808 fix: fallback to template filename if sanitized name is empty
  src/Model/Post.php
  src/Type/InterfaceType/ContentTemplate.php
  src/Utils/Utils.php
  tests/_data/templates/custom-i18n.php
  tests/_data/templates/custom.php
  tests/_data/templates/תבנית-שלי.php
  tests/wpunit/ContentTemplateTest.php
  tests/wpunit/PostObjectQueriesTest.php
Labels: type: bug, status: in review, scope: i18n

#2940 fix: Decode slug so it works with other languages
  src/Model/Menu.php
  src/Model/Term.php
  tests/wpunit/MenuQueriesTest.php
  tests/wpunit/TermObjectQueriesTest.php
Labels: type: bug, status: in review, needs: reviewer response, scope: i18n

#2958 feat: add `graphql_format_name()` access method
  access-functions.php
  src/Data/DataSource.php
  src/Mutation/UpdateSettings.php
  src/Type/ObjectType/SettingGroup.php
  src/Type/ObjectType/Settings.php
  src/Type/WPEnumType.php
  src/Utils/Utils.php
  tests/wpunit/AccessFunctionsTest.php
Labels: type: enhancement, status: in review, scope: API

#2967 fix: use all roles for `UserRoleEnum` instead of the filtered `editible_roles`
  src/Type/Enum/UserRoleEnum.php
Labels: type: bug, status: in review

#2962 fix: respect `hasPublishedPosts` where arg on unauthenticated `users` queries
  src/Data/Connection/UserConnectionResolver.php
  tests/wpunit/UserConnectionPaginationTest.php
  tests/wpunit/UserConnectionQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: type: bug, status: in review, Component: Connections, ObjectType: User

#2937 fix: Support asPreview by URI/SLUG Id Type
  composer.lock
  src/Data/NodeResolver.php
  src/Type/ObjectType/RootQuery.php
  src/Utils/Utils.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/PreviewContentNodesTest.php
  tests/wpunit/PreviewTest.php
Labels: status: awaiting author response
