Repository wp-graphql/wp-graphql, pull requests merged in 2023-08, with the labels that each got.

#2892 chore: GitHub template tweaks
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint-pr.yml
Labels: scope: docs, status: in review, type: chore

#2891 chore: bump graphql-php to 14.11.10 and update Composer dev-deps
  composer.json
  composer.lock
Labels: status: in review, scope: dependencies, type: chore

#2897 fix: default `excerptRendered` to empty string
  src/Model/Post.php
Labels: type: bug, status: in review
