Repository wp-graphql/wp-graphql, pull requests merged in 2023-11, with the labels that each got.

#2976 chore: restore commenting sniffs to PHPCS ruleset
  access-functions.php
  phpcs.xml.dist
  src/Admin/Settings/SettingsRegistry.php
  src/AppContext.php
  src/Data/CommentMutation.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Cursor/CommentObjectCursor.php
  src/Data/Cursor/TermObjectCursor.php
  src/Data/Cursor/UserCursor.php
  src/Data/DataSource.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Data/UserMutation.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/PostObjectDelete.php
  src/Mutation/TermObjectCreate.php
  src/Mutation/TermObjectDelete.php
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Router.php
  src/Server/ValidationRules/QueryDepth.php
  src/Server/ValidationRules/RequireAuthentication.php
  src/Type/Connection/PostObjects.php
  src/Type/ObjectType/PostObject.php
  src/Type/ObjectType/SettingGroup.php
  src/Type/WPConnectionType.php
  src/Type/WPInputObjectType.php
  src/Type/WPInterfaceType.php
  src/Type/WPMutationType.php
  src/Type/WPObjectType.php
  src/Type/WPScalar.php
  src/Type/WPUnionType.php
  src/Utils/DebugLog.php
  src/Utils/InstrumentSchema.php
  src/Utils/QueryAnalyzer.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/Utils/Utils.php
  src/WPGraphQL.php
  src/WPSchema.php
Labels: status: in review, needs: reviewer response, type: chore, scope: code quality

#2973 chore: update composer deps to latest
  composer.json
  composer.lock
Labels: status: in review, needs: reviewer response, scope: dependencies, type: chore

#2975 chore: lint and remove useless variables [phpcs]
  phpcs.xml.dist
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Model/UserRole.php
  src/Type/Connection/MenuItems.php
  src/Type/Connection/TermObjects.php
Labels: status: in review, needs: reviewer response, type: chore, scope: code quality

#2977 chore: sort `use` statements alphabetically with `SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses` (autofix)
  phpcs.xml.dist
  src/Data/Config.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/DataSource.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Data/PostObjectMutation.php
  src/Data/TermObjectMutation.php
  src/Model/Post.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/PostObjectDelete.php
  src/Mutation/PostObjectUpdate.php
  src/Mutation/TermObjectCreate.php
  src/Mutation/TermObjectDelete.php
  src/Mutation/TermObjectUpdate.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Router.php
  src/Type/Connection/PostObjects.php
  src/Type/ObjectType/PostObject.php
  src/WPGraphQL.php
Labels: status: in review, needs: reviewer response, type: chore, scope: code quality

#2984 ci: run tests against WordPress 6.4
  .github/workflows/graphiql-e2e-tests.yml
  .github/workflows/testing-integration.yml
  package-lock.json
  readme.txt
  tests/e2e/setup-test-framework.js
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/ThemeObjectQueriesTest.php
  wp-graphql.php
Labels: scope: tests

#2986 release: v1.18.1
  .github/workflows/graphiql-e2e-tests.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  package-lock.json
  readme.txt
  tests/e2e/setup-test-framework.js
  tests/wpunit/PostTypeObjectQueriesTest.php
  tests/wpunit/ThemeObjectQueriesTest.php
  wp-graphql.php
Labels: Release

#2987 release: v1.18.2
  .github/workflows/deploy-docker-image.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  readme.txt
  wp-graphql.php
Labels: Release

#2992 fix: add polyfills for `str_starts_with()` and `str_ends_with()` to prevent fatal errors in PHP < 8.0
  access-functions.php
Labels: type: bug, php

#2989 fix: make `User.url` public
  src/Model/User.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: type: bug, status: in review, ObjectType: User

#2988 feat: add missing extra fields to `EnqueuedAsset`, `EnqueuedScript` and `EnqueuedStylesheet`
  src/Registry/TypeRegistry.php
  src/Type/Enum/ScriptLoadingStrategyEnum.php
  src/Type/InterfaceType/EnqueuedAsset.php
  src/Type/ObjectType/EnqueuedScript.php
  src/Type/ObjectType/EnqueuedStylesheet.php
  tests/wpunit/RegisteredScriptConnectionQueriesTest.php
  tests/wpunit/RegisteredStylesheetConnectionQueriesTest.php
Labels: type: enhancement, status: in review

#2998 Update build-your-first-wpgraphql-extension.md
  docs/build-your-first-wpgraphql-extension.md
Labels: scope: docs, Type: Chore
