Repository wp-graphql/wp-graphql, pull requests merged in 2023-07, with the labels that each got.

#2854 release: v1.14.7
  .github/workflows/deploy-docker-image.yml
  .github/workflows/testing-integration.yml
  CHANGELOG.md
  package-lock.json
  readme.txt
  src/Admin/Settings/Settings.php
  src/Data/NodeResolver.php
  src/Model/Post.php
  src/Server/ValidationRules/QueryDepth.php
  src/WPGraphQL.php
  tests/wpunit/PostObjectQueriesTest.php
  wp-graphql.php
Labels: Release

#2856 chore: add missing translator comments
  phpcs.xml.dist
  src/Admin/Settings/Settings.php
  src/AppContext.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/DataSource.php
  src/Model/MenuItem.php
  src/Model/Model.php
  src/Mutation/MediaItemCreate.php
  src/Mutation/MediaItemDelete.php
  src/Mutation/PostObjectCreate.php
  src/Mutation/TermObjectCreate.php
  src/Mutation/UpdateSettings.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Server/ValidationRules/RequireAuthentication.php
  src/Type/Enum/CommentStatusEnum.php
  src/Type/Enum/ContentTypeEnum.php
  src/Type/Enum/MediaItemSizeEnum.php
  src/Type/Enum/MediaItemStatusEnum.php
  src/Type/Enum/MenuLocationEnum.php
  src/Type/Enum/MimeTypeEnum.php
  src/Type/Enum/PostStatusEnum.php
  src/Type/Enum/TaxonomyEnum.php
  src/Type/Enum/TimezoneEnum.php
  src/Type/ObjectType/RootQuery.php
  src/Type/ObjectType/SettingGroup.php
  src/Type/ObjectType/Settings.php
  src/Type/WPConnectionType.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPMutationType.php
  src/Utils/QueryLog.php
  src/WPGraphQL.php
Labels: status: in review, type: chore, scope: i18n

#2870 fix: type loader returns null when graphql_single_name value has underscores [regression]
  src/Utils/QueryAnalyzer.php
  tests/wpunit/CustomPostTypeTest.php
Labels: Regression
