Repository wp-graphql/wp-graphql, pull requests merged in 2023-09, with the labels that each got.

#2256 feat: add `connectedTerms` connection to Taxonomy object
  src/Type/ObjectType/Taxonomy.php
  tests/wpunit/TaxonomyObjectQueriesTest.php
Labels: status: in review, stale?

#2934 chore: use `.php` extension for stubfiles
  composer.lock
  phpcs.xml.dist
  phpstan.neon.dist
  phpstan/class-wp-dependency.php
  phpstan/class-wp-post-type.php
  phpstan/class-wp-taxonomy.php
Labels: status: in review, scope: build scripts, type: chore

#2932 chore: cleanup PHPCS inline annotations
  composer.lock
  src/Admin/Admin.php
  src/Admin/GraphiQL/GraphiQL.php
  src/Admin/Settings/Settings.php
  src/AppContext.php
  src/Data/Config.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Cursor/AbstractCursor.php
  src/Data/Cursor/PostObjectCursor.php
  src/Data/Cursor/TermObjectCursor.php
  src/Data/Cursor/UserCursor.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/PostObjectLoader.php
  src/Data/Loader/UserLoader.php
  src/Data/TermObjectMutation.php
  src/Mutation/MediaItemCreate.php
  src/Mutation/PostObjectCreate.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Request.php
  src/Router.php
  src/Type/Connection/Comments.php
  src/Type/Connection/MenuItems.php
  src/Type/Connection/PostObjects.php
  src/Type/InterfaceType/Commenter.php
  src/Type/InterfaceType/Edge.php
  src/Type/InterfaceType/MenuItemLinkable.php
  src/Type/InterfaceType/OneToOneConnection.php
  src/Type/InterfaceType/PageInfo.php
  src/Type/ObjectType/EnqueuedScript.php
  src/Type/ObjectType/EnqueuedStylesheet.php
  src/Type/WPConnectionType.php
  src/Type/WPMutationType.php
  src/Utils/DebugLog.php
  src/Utils/InstrumentSchema.php
  src/Utils/QueryAnalyzer.php
  src/Utils/QueryLog.php
  src/Utils/Tracing.php
  src/WPGraphQL.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/NodesTest.php
  tests/wpunit/PreviewTest.php
  tests/wpunit/SettingsMutationsTest.php
  tests/wpunit/TermObjectCursorTest.php
  tests/wpunit/TracingTest.php
  tests/wpunit/UtilsTest.php
Labels: status: in review, type: chore, scope: code quality

#2935 fix: admin notice if composer dependencies not installed
  build/app.asset.php
  build/app.js
  composer.json
  composer.lock
  constants.php
  phpstan.neon.dist
  src/WPGraphQL.php
  wp-graphql.php
Labels: status: in review, needs: reviewer response
