Repository wp-graphql/wp-graphql, pull requests merged in 2023-02, with the labels that each got.

#2707 ci: update and fix Lint PR workflow
  .github/workflows/lint-pr.yml
Labels: status: in review, type: chore

#2706 fix: update PHPStan and fix newly-surfaced sniffs
  access-functions.php
  composer.json
  composer.lock
  src/Data/Config.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/NodeResolver.php
  src/Request.php
  src/Utils/InstrumentSchema.php
  src/Utils/Tracing.php
Labels: type: bug, status: in review, scope: code quality

#2704 fix: missing apostrophe after escape
  src/Type/Enum/UsersConnectionSearchColumnEnum.php
Labels: type: bug, status: in review

#2701 fix: navigation url from request-lifecycle to wpgraphql-request-life…
  docs/docs_nav.json
Labels: type: bug, scope: docs, status: in review

#2718 fix: deprecation notice
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
Labels: type: bug, status: in review

#2728 release: v1.13.9
  CHANGELOG.md
  readme.txt
  src/Type/WPConnectionType.php
  src/WPGraphQL.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  wp-graphql.php
Labels: Release

#2680 feat: Refactor NodeResolver::resolve_uri() to use WP_Query
  src/Data/NodeResolver.php
  src/Type/ObjectType/RootQuery.php
  tests/wpunit/ContentNodeInterfaceTest.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/PageByUriTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/TermNodeTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
Labels: type: enhancement, Architecture, status: in progress

#2651 feat: add `deregister_graphql_mutation()` and corresponding `graphql_excluded_mutations` filter
  access-functions.php
  src/Data/NodeResolver.php
  src/Registry/TypeRegistry.php
  src/Type/WPMutationType.php
  tests/wpunit/AccessFunctionsTest.php
Labels: type: enhancement, status: in review, Component: Mutations, scope: API
