Repository wp-graphql/wp-graphql, pull requests merged in 2024-04, with the labels that each got.

#3073 feat: expose `hasPassword` and `password` fields on Post objects
  src/Model/Post.php
  src/Registry/Utils/PostObject.php
  tests/wpunit/PostObjectQueriesTest.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, ObjectType: Post

#3084 perf: refactor `PluginConnectionResolver` to only fetch plugins once
  src/Data/Connection/PluginConnectionResolver.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, ObjectType: Plugin

#3093 ci: Update actions in GitHub workflows and cleanup
  .github/workflows/build-graphiql.yml
  .github/workflows/code-quality.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docker-image.yml
  .github/workflows/deploy-to-wordpress.yml
  .github/workflows/graphiql-e2e-tests.yml
  .github/workflows/schema-linter.yml
  .github/workflows/sync-develop-with-master.yml
  .github/workflows/testing-integration.yml
  .github/workflows/upload-schema-artifact.yml
  .github/workflows/wordpress-coding-standards.yml
  bin/run-docker.sh
  docker-compose.yml
  tests/wpunit/CommentConnectionQueriesTest.php
Labels: Status: In Review, scope: build scripts, Type: Chore

#3082 chore: prepare ConnectionResolver classes for v2 backport
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
Labels: Status: In Review, Needs: Reviewer Response, Component: Connections, Type: Chore, scope: code quality

#3088 refactor: improve `loader` handling in `AbstractConnectionResolver`
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3087 feat: improve query amount handling in `AbstractConnectionResolver`
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3086 refactor: add `AbstractConnectionResolver::get_unfiltered_args()` public getter
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3085 refactor: add `AbstractConnectionResolver::prepare_page_info()`and only instantiate once
  src/Data/Connection/AbstractConnectionResolver.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3083 refactor: deprecate `camelCase` methods in `AbstractConnectionResolver` for `snake_case` equivalents
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
Labels: Type: Enhancement, Needs: Reviewer Response, Status: Blocked, Component: Connections, scope: code quality

#3095 chore: lint for superfluous whitespace
  phpcs.xml.dist
  src/Admin/Settings/SettingsRegistry.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/TaxonomyLoader.php
  src/Data/Loader/UserLoader.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Router.php
  src/Type/Connection/TermObjects.php
  src/Type/Connection/Users.php
  src/Type/WPConnectionType.php
Labels: Status: In Review, Needs: Reviewer Response, Status: Blocked, Type: Chore, scope: code quality

#3102 release: v1.24.0
  CHANGELOG.md
  constants.php
  phpcs.xml.dist
  readme.txt
  src/Admin/Settings/SettingsRegistry.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Data/Loader/AbstractDataLoader.php
  src/Data/Loader/TaxonomyLoader.php
  src/Data/Loader/UserLoader.php
  src/Data/MediaItemMutation.php
  src/Data/NodeResolver.php
  src/Registry/TypeRegistry.php
  src/Router.php
  src/Type/Connection/TermObjects.php
  src/Type/Connection/Users.php
  src/Type/WPConnectionType.php
  src/Type/WPInterfaceTrait.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  wp-graphql.php
Labels: Release
