Repository wp-graphql/wp-graphql, pull requests merged in 2024-08, with the labels that each got.

#3181 ci: replace `docker-compose` commands with `docker compose`
  bin/run-docker.sh
  composer.json
  docs/testing.md
Labels: Status: In Review, scope: build scripts, Needs: Reviewer Response, Type: Chore

#3184 release: v1.28.0
  CHANGELOG.md
  composer.lock
  constants.php
  readme.txt
  wp-graphql.php
Labels: Release

#3189 fix: [regression] missing placeholder in $wpdb->prepare
  src/Data/Loader/UserLoader.php
Labels: Type: Bug, Status: In Review, Needs: Reviewer Response, Regression

#3193 release: v1.28.1
  CHANGELOG.md
  constants.php
  readme.txt
  src/Data/Loader/UserLoader.php
  wp-graphql.php
Labels: Release
