Repository wp-graphql/wp-graphql, pull requests merged in 2024-06, with the labels that each got.

#3146 test: Add e2e test coverage for tabs in the settings page
  .wp-env.json
  tests/e2e/plugins/README.md
  tests/e2e/plugins/settings-page-spec/settings-page-spec.php
  tests/e2e/specs/settings-page.spec.js
  tests/e2e/utils.js
Labels: scope: tests

#3149 release: v1.27.0
  .distignore
  .gitattributes
  .wp-env.json
  CHANGELOG.md
  access-functions.php
  constants.php
  readme.txt
  src/Admin/GraphiQL/GraphiQL.php
  src/Admin/Settings/SettingsRegistry.php
  src/WPGraphQL.php
  tests/e2e/plugins/README.md
  tests/e2e/plugins/settings-page-spec/settings-page-spec.php
  tests/e2e/specs/settings-page.spec.js
  tests/e2e/utils.js
  wp-graphql.php
Labels: Release

#3152 fix: handle regression when implementing interface with identical args.
  src/Registry/Utils/PostObject.php
  src/Type/WPInterfaceTrait.php
  tests/wpunit/InterfaceTest.php
Labels: Status: In Review, Needs: Reviewer Response, Component: Interfaces, Regression

#3151 fix: update dev-deps and fix `WPGraphQL::get_static_schema()`
  composer.json
  composer.lock
  src/WPGraphQL.php
Labels: Status: In Review, Needs: Reviewer Response, scope: code quality
