Repository wp-graphql/wp-graphql, pull requests merged in 2024-12, with the labels that each got.

#3243 chore: fix Composer autoloader for `WPGraphQL.php`
  composer.json
Labels: status: in review, needs: reviewer response

#3249 release: v1.29.3
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  constants.php
  docs/quick-start.md
  img/graphiql-ide-example.gif
  phpstan.neon.dist
  phpstan/constants.php
  readme.txt
  src/Data/NodeResolver.php
  wp-graphql.php
Labels: type: release

#3262 chore: update docs & improve comment functionality
  docs/authentication-and-authorization.md
  docs/build-your-first-wpgraphql-extension.md
  docs/categories-and-tags.md
  docs/comments.md
  docs/performance.md
  src/Data/Connection/CommentConnectionResolver.php
  src/Model/Post.php
  src/Type/Connection/Comments.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/CommentObjectQueriesTest.php
Labels: scope: docs, component: mutations, object type: comment

#3263 chore: update PHPCS and format `/tests`
  composer.lock
  phpcs.xml.dist
  tests/_data/classes/WP_Query_Custom.php
  tests/e2e/plugins/settings-page-spec/settings-page-spec.php
  tests/functional/GraphQLHeadersCept.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/AdminNoticesTest.php
  tests/wpunit/CommentConnectionQueriesTest.php
  tests/wpunit/CommentMutationsTest.php
  tests/wpunit/CommentObjectQueriesTest.php
  tests/wpunit/ConnectionRegistrationTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/MenuItemQueriesTest.php
  tests/wpunit/ModelUserTest.php
  tests/wpunit/NodeByUriTest.php
  tests/wpunit/PageByUriTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectCursorTest.php
  tests/wpunit/PostObjectQueriesTest.php
  tests/wpunit/PreviewContentNodesTest.php
  tests/wpunit/PreviewTest.php
  tests/wpunit/QueryAnalyzerTest.php
  tests/wpunit/RequestTest.php
  tests/wpunit/TermNodeTest.php
  tests/wpunit/TermObjectConnectionQueriesTest.php
  tests/wpunit/TermObjectCursorTest.php
  tests/wpunit/TermObjectQueriesTest.php
  tests/wpunit/UserConnectionQueriesTest.php
  tests/wpunit/UserObjectQueriesTest.php
  tests/wpunit/UtilsTest.php
Labels: status: in review, needs: reviewer response, type: chore

#3268 ci: trigger PR workflows on `release/*` branches
  .github/workflows/code-quality.yml
  .github/workflows/graphiql-e2e-tests.yml
  .github/workflows/schema-linter.yml
  .github/workflows/testing-integration.yml
  .github/workflows/wordpress-coding-standards.yml
Labels: status: in review, scope: build scripts, needs: reviewer response, type: chore

#3267 chore: fix bleeding edge/deprecated PHPStan smells [first pass]
  composer.json
  composer.lock
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Cursor/AbstractCursor.php
  src/Data/UserMutation.php
  src/Model/Menu.php
  src/Model/Term.php
  src/Model/Theme.php
  src/Mutation/MediaItemCreate.php
  src/Registry/TypeRegistry.php
  src/Utils/InstrumentSchema.php
  src/Utils/QueryAnalyzer.php
Labels: status: in review, needs: reviewer response, type: chore, scope: code quality
