Repository wp-graphql/wp-graphql, pull requests merged in 2024-07, with the labels that each got.

#3066 fix: stop overwrite tax query filter if it exists
  src/Data/Connection/AbstractConnectionResolver.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
Labels: Type: Enhancement, Status: Discussion, Compat: Breaking Change, Needs: Info, Needs: Reviewer Response

#3163 release: v1.27.1
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  constants.php
  img/logo.png
  img/wp-graphql-logo-square-512x512.png
  img/wp-graphql-logo-square.svg
  img/wpgraphql-elephant.svg
  package-lock.json
  readme.txt
  src/Admin/GraphiQL/GraphiQL.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Type/WPInterfaceTrait.php
  src/WPGraphQL.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  wp-graphql.php
Labels: Release

#3168 release: v1.27.2
  CHANGELOG.md
  constants.php
  img/README.md
  readme.txt
  src/Admin/GraphiQL/GraphiQL.php
  src/assets/README.md
  src/assets/wpgraphql-elephant.svg
  wp-graphql.php
Labels: Release

#3172 fix: only `eagerlyLoadType` on introspection requests
  cli/wp-cli.php
  src/Registry/TypeRegistry.php
  src/Request.php
  src/Utils/QueryAnalyzer.php
  src/WPGraphQL.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/AssertValidSchemaTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/PostObjectMutationsTest.php
  tests/wpunit/RequestTest.php
Labels: Compat: Possible Break
