Repository wp-graphql/wp-graphql, pull requests merged in 2024-05, with the labels that each got.

#3104 refactor: make `AbstractConnectionResolver::should_execute()` non-abstract and add `::pre_should_execute()`
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3118 release: v1.25.0
  CHANGELOG.md
  composer.json
  composer.lock
  constants.php
  readme.txt
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Loader/AbstractDataLoader.php
  src/Type/WPInterfaceTrait.php
  tests/wpunit/AccessFunctionsTest.php
  tests/wpunit/CommentConnectionQueriesTest.php
  tests/wpunit/ConnectionRegistrationTest.php
  tests/wpunit/ContentTypeConnectionQueriesTest.php
  tests/wpunit/CustomPostTypeTest.php
  tests/wpunit/CustomTaxonomyTest.php
  tests/wpunit/InterfaceTest.php
  tests/wpunit/MenuConnectionQueriesTest.php
  tests/wpunit/MenuItemConnectionQueriesTest.php
  tests/wpunit/PluginConnectionQueriesTest.php
  tests/wpunit/PostConnectionPaginationTest.php
  tests/wpunit/QueryAnalyzerTest.php
  tests/wpunit/RegisteredScriptConnectionQueriesTest.php
  tests/wpunit/RegisteredStylesheetConnectionQueriesTest.php
  tests/wpunit/TaxonomyConnectionQueriesTest.php
  tests/wpunit/TermObjectConnectionQueriesTest.php
  tests/wpunit/ThemeConnectionQueriesTest.php
  tests/wpunit/TracingTest.php
  tests/wpunit/UserConnectionPaginationTest.php
  tests/wpunit/UserRoleConnectionQueriesTest.php
  wp-graphql.php
Labels: Release

#3120 refactor: wrap `AbstractConnectionResolver::is_valid_model()` in `::get_is_valid_model()`
  src/Data/Connection/AbstractConnectionResolver.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
Labels: Type: Enhancement, Status: In Review, Needs: Reviewer Response, Component: Connections, scope: API

#3122 chore: relocate `AbstractConnectionResolver::is_valid_offset()` with other abstract methods.
  src/Data/Connection/AbstractConnectionResolver.php
Labels: Status: In Review, Needs: Reviewer Response, Component: Connections, Type: Chore, scope: code quality

#3131 chore: cleanup AbstractConnectionResolver before release.
  access-functions.php
  composer.lock
  src/Admin/Settings/SettingsRegistry.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Mutation/PostObjectDelete.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Request.php
  src/Type/ObjectType/PostObject.php
  src/Utils/QueryAnalyzer.php
  src/WPGraphQL.php
  tests/_data/classes/WP_Query_Custom.php
  wp-graphql.php
Labels: Status: In Review, Needs: Reviewer Response, Type: Chore, scope: code quality

#3129 release: v1.26.0
  CHANGELOG.md
  README.md
  access-functions.php
  build/app.asset.php
  build/app.js
  composer.lock
  constants.php
  packages/wpgraphiql/screens/Help/Help.js
  readme.txt
  src/Admin/Settings/SettingsRegistry.php
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/CommentConnectionResolver.php
  src/Data/Connection/ContentTypeConnectionResolver.php
  src/Data/Connection/EnqueuedScriptsConnectionResolver.php
  src/Data/Connection/EnqueuedStylesheetConnectionResolver.php
  src/Data/Connection/MenuConnectionResolver.php
  src/Data/Connection/MenuItemConnectionResolver.php
  src/Data/Connection/PluginConnectionResolver.php
  src/Data/Connection/PostObjectConnectionResolver.php
  src/Data/Connection/TaxonomyConnectionResolver.php
  src/Data/Connection/TermObjectConnectionResolver.php
  src/Data/Connection/ThemeConnectionResolver.php
  src/Data/Connection/UserConnectionResolver.php
  src/Data/Connection/UserRoleConnectionResolver.php
  src/Data/Cursor/CursorBuilder.php
  src/Mutation/PostObjectDelete.php
  src/Registry/TypeRegistry.php
  src/Registry/Utils/PostObject.php
  src/Registry/Utils/TermObject.php
  src/Request.php
  src/Type/ObjectType/PostObject.php
  src/Utils/QueryAnalyzer.php
  src/WPGraphQL.php
  tests/_data/classes/WP_Query_Custom.php
  tests/_data/classes/WP_Query_Incompatible.php
  tests/wpunit/ConnectionRegistrationTest.php
  tests/wpunit/PostObjectConnectionQueriesTest.php
  tests/wpunit/PostObjectCursorTest.php
  wp-graphql.php
Labels: Release

#3058 fix: prevent wpml from redirecting in WPGraphQL requests
  src/WPGraphQL.php
Labels: WPML
