Repository wp-graphql/wp-graphql, pull requests merged in 2025-02, with the labels that each got.

#3289 fix: [v2.0] Cleanup PHPStan type coercions and fix underlying issues (second pass)
  .github/workflows/deploy-docker-image.yml
  phpcs.xml.dist
  src/Registry/TypeRegistry.php
  src/Type/WPConnectionType.php
  src/Type/WPInputObjectType.php
  src/Type/WPInterfaceType.php
  src/Type/WPObjectType.php
  src/Type/WPUnionType.php
Labels: status: in review, needs: reviewer response

#3291 fix: return 415 status code for missing or invalid content type header
  src/Request.php
  src/Router.php
  tests/functional/ContentTypeHeaderCept.php
Labels: compat: breaking change

#3293 fix: correct the resolver for the MediaDetails.file field to return the file name
  src/Type/ObjectType/MediaDetails.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
Labels: type: bug, object type: media

#3299 chore: restore excluded PHPCS rules
  phpcs.xml.dist
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Loader/AbstractDataLoader.php
Labels: status: in review, needs: reviewer response

#3301 fix: React backwards-compatibility with WP < 6.6
  build/app.asset.php
  build/app.js
  build/extensions.asset.php
  build/extensions.js
  build/graphiqlAuthSwitch.asset.php
  build/graphiqlAuthSwitch.js
  build/graphiqlFullscreenToggle.asset.php
  build/graphiqlFullscreenToggle.js
  build/graphiqlQueryComposer.asset.php
  build/graphiqlQueryComposer.js
  build/index.asset.php
  build/index.js
  package-lock.json
  package.json
  packages/extensions/index.js
  packages/wpgraphiql/app.js
Labels: status: in review, needs: reviewer response, regression

#3297 fix: typo in `Extensions\Registry\get_extensions()` method name
  docs/submit-extension.md
  src/Admin/Extensions/Extensions.php
  src/Admin/Extensions/Registry.php
  src/Request.php
Labels: status: in review, needs: reviewer response, regression

#3294 feat: introduce new fields for getting mediaItem files and filePaths
  src/Registry/Utils/PostObject.php
  src/Type/ObjectType/MediaDetails.php
  src/Type/ObjectType/MediaSize.php
  tests/wpunit/MediaItemQueriesTest.php
Labels: object type: media

#3303 chore: cleanup git cache
  codeception.dist.yml
  codeception.yml
  tests/.gitignore
  tests/_data/.gitkeep
  tests/_data/images/.gitignore
  tests/_data/images/2000x1000.png
  tests/_data/images/mgc.gif
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/MediaItemQueriesTest.php
  wp-graphql.php
Labels: status: in review, needs: reviewer response

#3295 chore: (v2.0) remove php-coveralls from dev-dependencies
  .coveralls.yml
  .distignore
  .github/workflows/testing-integration.yml
  .gitignore
  composer.json
  composer.lock
Labels: status: in review, needs: reviewer response

#3310 release: v1.32.1
  CHANGELOG.md
  constants.php
  package.json
  readme.txt
  src/Data/TermObjectMutation.php
  src/Mutation/TermObjectCreate.php
  src/Utils/Utils.php
  tests/wpunit/TermObjectMutationsTest.php
  wp-graphql.php
Labels: type: release

#3190 docs: add developer docs for `AbstractConnectionResolver`
  src/Data/Connection/AbstractConnectionResolver.php
  src/Data/Connection/README.md
Labels: status: in review, needs: reviewer response

#3314 fix: use `version_compare` to simplify incompatible dependent check
  src/Admin/Updates/UpdateChecker.php
Labels: status: in review, needs: reviewer response, regression

#3316 docs: update changelog and upgrade notice
  CHANGELOG.md
  readme.txt
Labels: scope: docs
