Repository wp-graphql/wp-graphql, pull requests merged in 2025-01, with the labels that each got.

#3251 feat: implement SemVer-compliant update checker
  build/updates.asset.php
  build/updates.css
  package-lock.json
  package.json
  packages/updates/index.scss
  src/Admin/Updates/PluginsScreenLoader.php
  src/Admin/Updates/SemVer.php
  src/Admin/Updates/UpdateChecker.php
  src/Admin/Updates/Updates.php
  src/Admin/Updates/UpdatesScreenLoader.php
  src/WPGraphQL.php
  tests/_data/plugins/plugin-incompatible-version.php
  tests/_data/plugins/plugin-with-headers.php
  tests/_data/plugins/plugin-with-meta.php
  tests/_data/plugins/plugin-with-requires.php
  tests/wpunit/MediaItemMutationsTest.php
  tests/wpunit/SemVerTest.php
  tests/wpunit/UpdatesTest.php
  webpack.config.js
Labels: status: in progress, type: feature

#3196 feat: expose `EnqueuedAsset.group` and `EnqueuedScript.location` to schema
  src/Registry/TypeRegistry.php
  src/Type/Enum/ScriptLoadingGroupLocationEnum.php
  src/Type/InterfaceType/EnqueuedAsset.php
  src/Type/ObjectType/EnqueuedScript.php
  tests/wpunit/RegisteredScriptConnectionQueriesTest.php
  tests/wpunit/RegisteredStylesheetConnectionQueriesTest.php
Labels: status: in review, needs: reviewer response

#3285 release: v1.31.0
  CHANGELOG.md
  cli/wp-cli.php
  constants.php
  docs/menus.md
  readme.txt
  src/Admin/Updates/Updates.php
  wp-graphql.php
Labels: type: release
